# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_ngame-for-msmarco-inference.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/00_ngame-for-msmarco-inference.ipynb 3
import os, torch,json, torch.multiprocessing as mp, joblib, numpy as np, scipy.sparse as sp, argparse

from xcai.basics import *
from xcai.misc import *
from xcai.models.PPP0XX import DBT009, DBTConfig

# %% ../nbs/00_ngame-for-msmarco-inference.ipynb 20
if __name__ == '__main__':
    output_dir = "/data/outputs/upma/00_msmarco-gpt-concept-substring-linker-with-ngame-loss-001"

    input_args = parse_args()
    extra_args = additional_args()

    input_args.use_sxc_sampler = True
    input_args.do_test_inference = True
    input_args.save_test_prediction = True
    input_args.pickle_dir = "/home/aiscuser/scratch1/datasets/processed/"

    mname = "sentence-transformers/msmarco-distilbert-cos-v5"
    do_inference = check_inference_mode(input_args)
    dataset_prefix = input_args.dataset.replace("/", "-")

    # test-data
    test_info = load_info(f"{input_args.pickle_dir}/beir/{dataset_prefix}.joblib",
                          f"/data/datasets/beir/{input_args.dataset}/XC/raw_data/test.raw.csv",
                          mname, sequence_length=32)

    # meta-data
    if extra_args.use_task_specific_metadata:
        meta_info = load_info(f"{input_args.pickle_dir}/beir/{dataset_prefix}_document-substring_sq-substring.joblib",
                              f"/data/datasets/beir/{input_args.dataset}/XC/document_substring/raw_data/sq-substring.raw.csv",
                              mname, sequence_length=64)
    else:
        meta_info = load_info(f"{input_args.pickle_dir}/msmarco-substring-metadata.joblib",
                              "/data/datasets/beir/msmarco/XC/substring/raw_data/substring.raw.csv",
                              mname, sequence_length=64)

    # dataset
    test_dset = SXCDataset(SMainXCDataset(data_info=test_info, lbl_info=meta_info))

    args = XCLearningArguments(
        output_dir=output_dir,
        logging_first_step=True,
        per_device_train_batch_size=800,
        per_device_eval_batch_size=800,
        representation_num_beams=200,
        representation_accumulation_steps=10,
        save_strategy="steps",
        eval_strategy="steps",
        eval_steps=5000,
        save_steps=5000,
        save_total_limit=5,
        num_train_epochs=300,
        predict_with_representation=True,
        representation_search_type='BRUTEFORCE',
        adam_epsilon=1e-6,
        warmup_steps=100,
        weight_decay=0.01,
        learning_rate=2e-4,

        group_by_cluster=True,
        num_clustering_warmup_epochs=10,
        num_cluster_update_epochs=5,
        num_cluster_size_update_epochs=25,
        clustering_type='EXPO',
        minimum_cluster_size=2,
        maximum_cluster_size=1600,

        metric_for_best_model='N@10',
        load_best_model_at_end=True,
        target_indices_key='plbl2data_idx',
        target_pointer_key='plbl2data_data2ptr',

        use_encoder_parallel=True,
        max_grad_norm=None,
        fp16=True,

        use_cpu_for_searching=True,
        use_cpu_for_clustering=True,
    )

    config = DBTConfig(
        margin = 0.3,
        num_negatives = 10,
        tau = 0.1,
        apply_softmax = True,
        reduction = "mean",

        normalize = True,
        use_layer_norm = True,

        use_encoder_parallel = True,
        loss_function = "triplet"
    )

    def model_fn(mname, config):
        return DBT009.from_pretrained(mname, config=config)

    model = load_model(args.output_dir, model_fn, {"mname": mname, "config": config}, do_inference=do_inference,
                       use_pretrained=input_args.use_pretrained)

    learn = XCLearner(
        model=model,
        args=args,
        train_dataset=None,
        eval_dataset=test_dset,
        data_collator=identity_collate_fn,
    )

    save_dir_name = "predictions_document-substring_sq-substring" if extra_args.use_task_specific_metadata else None
    main(learn, input_args, n_lbl=test_dset.data.n_lbl, eval_k=10, train_k=10, save_dir_name=save_dir_name)

