# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/37_training-msmarco-distilbert-from-scratch.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/37_training-msmarco-distilbert-from-scratch.ipynb 2
import os
os.environ["NCCL_DEBUG"] = "NONE"
os.environ["ROCM_DISABLE_WARNINGS"] = "1"
os.environ["MIOPEN_LOG_LEVEL"] = "0"

import torch,json, torch.multiprocessing as mp, joblib, numpy as np, scipy.sparse as sp

from typing import Optional
from transformers import DistilBertConfig
from xclib.utils.sparse import retain_topk

from xcai.basics import *
from xcai.models.upma import UPA000, UPMAConfig

# %% ../nbs/37_training-msmarco-distilbert-from-scratch.ipynb 21
if __name__ == '__main__':
    output_dir = "/data/outputs/upma/03_upma-with-ngame-gpt-substring-linker-for-msmarco-002"

    input_args = parse_args()
    extra_args = additional_args()

    input_args.only_test = True
    input_args.use_sxc_sampler = True
    input_args.do_test_inference = True
    input_args.save_test_prediction = True
    input_args.pickle_dir = "/home/aiscuser/scratch1/datasets/processed/"

    mname = "distilbert-base-uncased"
    do_inference = check_inference_mode(input_args)

    # basic dataset
    config_file = f"/data/datasets/beir/{input_args.dataset}/XC/configs/data.json"
    config_key, fname = get_config_key(config_file)
    pkl_file = get_pkl_file(input_args.pickle_dir, f"{input_args.dataset.replace('/', '-')}_{fname}_distilbert-base-uncased", input_args.use_sxc_sampler, 
                            input_args.exact, input_args.only_test)
    block = build_block(pkl_file, config_file, input_args.use_sxc_sampler, config_key, do_build=input_args.build_block, 
                        only_test=input_args.only_test, main_oversample=True, return_scores=True, n_slbl_samples=1) 

    # metadata dataset
    meta_info = load_info(f"{input_args.pickle_dir}/concept-substring.joblib",
                          "/data/datasets/beir/msmarco/XC/concept_substrings/raw_data/concept-substring.raw.csv", 
                          mname, sequence_length=64)
    pred_dir = f"/data/outputs/upma/00_msmarco-gpt-concept-substring-linker-with-ngame-loss-001/predictions/"
    data_meta = retain_topk(sp.load_npz(f"{pred_dir}/test_predictions_{input_args.dataset.replace('/', '-')}.npz"), k=5)
    meta_dataset = SMetaXCDataset(prefix="lnk", data_meta=data_meta, meta_info=meta_info, n_sdata_meta_samples=5, 
                                  return_scores=True, meta_oversample=False) 

    # test dataset
    test_dset = SXCDataset(block.test.dset.data, **{"lnk_meta": meta_dataset})

    args = XCLearningArguments(
        output_dir=output_dir,
        logging_first_step=True,
        per_device_train_batch_size=128,
        per_device_eval_batch_size=800,
        representation_num_beams=200,
        representation_accumulation_steps=10,
        save_strategy="steps",
        eval_strategy="steps",
        eval_steps=5000,
        save_steps=5000,
        save_total_limit=5,
        num_train_epochs=50,
        predict_with_representation=True,
        representation_search_type='BRUTEFORCE',
        search_normalize=False, 

        adam_epsilon=1e-6,
        warmup_steps=1000,
        weight_decay=0.01,
        learning_rate=6e-5,
        label_names=["plbl2data_idx", "plbl2data_data2ptr", "lnk2data_idx", "lnk2data_data2ptr", "lnk2data_scores"],
    
        group_by_cluster=True,
        use_data_metadata_for_clustering=True,
        num_clustering_warmup_epochs=10,
        num_cluster_update_epochs=5,
        num_cluster_size_update_epochs=25,
        clustering_type='EXPO',
        minimum_cluster_size=2,
        maximum_cluster_size=1600,

        data_aug_meta_name="lnk",
        use_label_metadata=False,
    
        metric_for_best_model='N@10',
        load_best_model_at_end=True,
        target_indices_key='plbl2data_idx',
        target_pointer_key='plbl2data_data2ptr',
    
        use_encoder_parallel=True,
        max_grad_norm=None,
        fp16=True,

        use_cpu_for_searching=True,
        use_cpu_for_clustering=True,
    )

    config = UPMAConfig(
        memory_module_names = ["embeddings"],
        memory_injection_layers = [6],
        
        num_total_metadata = test_dset.meta["lnk_meta"].n_meta,
        num_input_metadata = 5,
        metadata_dropout = 0.1,
        
        n_memory_layers = 3,
    
        data_aug_meta_prefix="lnk2data",
        lbl2data_aug_meta_prefix="lnk2lbl",
        neg2data_aug_meta_prefix="lnk2neg",
    
        data_inject_memory=True,
        lbl2data_inject_memory=False,
        neg2data_inject_memory=False,
        
        data_repr_pooling=True,
        data_normalize=False,
    
        margin=0.3,
        num_negatives=10,
        tau=0.1,
        apply_softmax=True,
        reduction="mean",
    
    	calib_margin=0.3,
        calib_num_negatives=10,
        calib_tau=0.1,
        calib_apply_softmax=False,
        
        calib_loss_weight=0.1,
        use_calib_loss=True,
        
        use_encoder_parallel=True,
        loss_function="margin",

    	initialize_memory_embeddings_from_injection_layer_mean=True,
        metadata_embedding_file=f"{output_dir}/metadata/gpt-substring.pth",
    )

    def model_fn(mname:Optional[str]=None):
        meta_dset = test_dset.meta_dset("lnk_meta")
        model = UPA000.from_pretrained(config, mname=mname, meta_dset=meta_dset, batch_size=1000)
        return model
    
    metric = PrecReclMrr(test_dset.n_lbl, block.test.data_lbl_filterer, pk=10, rk=200, rep_pk=[1, 3, 5, 10], 
                         rep_rk=[10, 100, 200], mk=[5, 10, 20])

    model = load_model(args.output_dir, model_fn, do_inference=do_inference, use_pretrained=input_args.use_pretrained)
    
    learn = XCLearner(
        model=model,
        args=args,
        train_dataset=None if block.train is None else block.train.dset,
        eval_dataset=test_dset,
        data_collator=block.collator,
        compute_metrics=metric,
    )

    main(learn, input_args, n_lbl=test_dset.n_lbl)
    
