# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/37_training-msmarco-distilbert-from-scratch.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/37_training-msmarco-distilbert-from-scratch.ipynb 2
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "0,1"

import torch,json, torch.multiprocessing as mp, joblib, numpy as np, scipy.sparse as sp, argparse
from typing import Optional, Union, Callable
from tqdm.auto import tqdm

from transformers import DistilBertConfig
from xclib.utils.sparse import retain_topk

from xcai.basics import *
from xcai.models.upma import UPA000, UPMAConfig

# %% ../nbs/37_training-msmarco-distilbert-from-scratch.ipynb 4
os.environ["WANDB_PROJECT"] = "02_upma-msmarco-gpt-concept-substring"


def run(output_dir:str, input_args:argparse.ArgumentParser, mname:str, test_dset:Union[XCDataset, SXCDataset], 
        train_dset:Optional[Union[XCDataset, SXCDataset]]=None, collator:Optional[Callable]=identity_collate_fn):

    args = XCLearningArguments(
        output_dir=output_dir,
        logging_first_step=True,
        per_device_train_batch_size=64,
        per_device_eval_batch_size=400,
        representation_num_beams=200,
        representation_accumulation_steps=10,
        save_strategy="steps",
        eval_strategy="steps",
        eval_steps=5000,
        save_steps=5000,
        save_total_limit=5,
        num_train_epochs=50,
        predict_with_representation=True,
        representation_search_type='BRUTEFORCE',
        search_normalize=False, 

        adam_epsilon=1e-6,
        warmup_steps=1000,
        weight_decay=0.01,
        learning_rate=6e-5,
        label_names=["plbl2data_idx", "plbl2data_data2ptr", "lnk2data_idx", "lnk2data_data2ptr", "lnk2data_scores"],
    
        group_by_cluster=True,
        use_data_metadata_for_clustering=True,
        num_clustering_warmup_epochs=10,
        num_cluster_update_epochs=5,
        num_cluster_size_update_epochs=25,
        clustering_type='EXPO',
        minimum_cluster_size=2,
        maximum_cluster_size=1600,

        data_aug_meta_name="lnk",
        use_label_metadata=False,
    
        metric_for_best_model='N@10',
        load_best_model_at_end=True,
        target_indices_key='plbl2data_idx',
        target_pointer_key='plbl2data_data2ptr',
    
        use_encoder_parallel=True,
        max_grad_norm=None,
        fp16=True,

        use_cpu_for_searching=True,
        use_cpu_for_clustering=True,
    )

    config = UPMAConfig(
        memory_module_names = ["embeddings"],
        memory_injection_layers = [6],
        
        num_total_metadata = test_dset.meta["lnk_meta"].n_meta,
        num_input_metadata = 5,
        metadata_dropout = 0.1,
        
        n_memory_layers = 3,
    
        data_aug_meta_prefix="lnk2data",
        lbl2data_aug_meta_prefix="lnk2lbl",
        neg2data_aug_meta_prefix="lnk2neg",
    
        data_inject_memory=True,
        lbl2data_inject_memory=False,
        neg2data_inject_memory=False,
        
        data_repr_pooling=True,
        data_normalize=False,
    
        margin=0.3,
        num_negatives=10,
        tau=0.1,
        apply_softmax=True,
        reduction="mean",
    
    	calib_margin=0.3,
        calib_num_negatives=10,
        calib_tau=0.1,
        calib_apply_softmax=False,
        
        calib_loss_weight=0.1,
        use_calib_loss=True,
        
        use_encoder_parallel=True,
        loss_function="margin",

    	initialize_memory_embeddings_from_injection_layer_mean=True,
        metadata_embedding_file=f"{output_dir}/metadata/gpt-substring.pth",
    )

    def model_fn(mname:Optional[str]=None):
        meta_dset = test_dset.meta_dset("lnk_meta")
        model = UPA000.from_pretrained(config, mname=mname, meta_dset=meta_dset, batch_size=1000)
        return model
    
    metric = PrecReclMrr(test_dset.n_lbl, test_dset.data.data_lbl_filterer, pk=10, rk=200, rep_pk=[1, 3, 5, 10], 
                         rep_rk=[10, 100, 200], mk=[5, 10, 20])

    model = load_model(args.output_dir, model_fn, do_inference=check_inference_mode(input_args), use_pretrained=input_args.use_pretrained)
    
    learn = XCLearner(
        model=model,
        args=args,
        train_dataset=train_dset,
        eval_dataset=test_dset,
        data_collator=collator,
        compute_metrics=metric,
    )

    return main(learn, input_args, n_lbl=test_dset.n_lbl)


def load_block(dataset:str, config_file:str, input_args:argparse.ArgumentParser):
    config_key, fname = get_config_key(config_file)
    pkl_file = get_pkl_file(input_args.pickle_dir, f"{dataset}_{fname}_distilbert-base-uncased", input_args.use_sxc_sampler, 
                            input_args.exact, input_args.only_test)

    os.makedirs(os.path.dirname(pkl_file), exist_ok=True)
    block = build_block(pkl_file, config_file, input_args.use_sxc_sampler, config_key, do_build=input_args.build_block, 
                        only_test=input_args.only_test, main_oversample=True, meta_oversample=True, return_scores=True, 
                        n_slbl_samples=1, n_sdata_meta_samples={"lnk_meta": 5, "neg_meta": 1}, 
                        train_meta_topk={"lnk_meta": 5}, test_meta_topk={"lnk_meta": 5})
    train_dset, test_dset = None if block.train is None else block.train.dset, block.test.dset

    return train_dset, test_dset 
    

def beir_inference(output_dir:str, input_args:argparse.ArgumentParser, mname:str):
    metric_dir = f"{output_dir}/metrics"
    os.makedirs(metric_dir, exist_ok=True)

    input_args.only_test = input_args.do_test_inference = input_args.save_test_prediction = True

    save_file = f"{input_args.pickle_dir}/category-gpt-linker_conflated-001_conflated-001.joblib"
    meta_file = "/data/datasets/beir/msmarco/XC/raw_data/category-gpt-linker_conflated-001_conflated-001.raw.csv"
    meta_info = load_info(save_file, meta_file, mname, sequence_length=64)

    beir_metrics = {}
    for dataset in tqdm(DATASETS):
        print(dataset)

        config_file = f"/data/datasets/beir/{dataset}/XC/configs/data.json"
        train_dset, test_dset = load_block(dataset, config_file, input_args)

        dataset = dataset.replace("/", "-")
        data_meta = retain_topk(sp.load_npz(f"/data/outputs/mogicX/47_msmarco-gpt-category-linker-007/predictions/test_predictions_{dataset}.npz"), k=5)
        meta_kwargs = {
            "lnk_meta": SMetaXCDataset(prefix="lnk", data_meta=data_meta, meta_info=meta_info, n_sdata_meta_samples=5, 
                                       return_scores=True, meta_oversample=True),
        }
        test_dset = SXCDataset(test_dset.data, **meta_kwargs)

        input_args.prediction_suffix = dataset
        trn_repr, tst_repr, lbl_repr, trn_pred, tst_pred, trn_metric, tst_metric = run(output_dir, input_args, mname, test_dset, train_dset)
        with open(f"{metric_dir}/{dataset}.json", "w") as file:
            json.dump({dataset: tst_metric}, file, indent=4)

        beir_metrics[dataset] = tst_metric

    with open(f"{metric_dir}/beir.json", "w") as file:
        json.dump(beir_metrics, file, indent=4)


# %% ../nbs/37_training-msmarco-distilbert-from-scratch.ipynb 21
if __name__ == '__main__':
    input_args = parse_args()

    output_dir = "/data/outputs/upma/04_upma-with-ngame-gpt-category-linker-for-msmarco-001"

    input_args.use_sxc_sampler = True
    input_args.pickle_dir = "/home/aiscuser/scratch1/datasets/processed/"
    mname = "distilbert-base-uncased"

    if input_args.beir_mode:
        beir_inference(output_dir, input_args, mname)
    else:
        config_file = (
            "configs/msmarco/data_lbl_ngame-gpt-category-linker_ce-negatives-topk-05-linker_exact.json"
            if input_args.exact else
            "configs/msmarco/data_lbl_ngame-gpt-category-linker.json"
        )
        train_dset, test_dset = load_block("msmarco", config_file, input_args)
        run(output_dir, input_args, mname, test_dset, train_dset)

