# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_ngame-for-msmarco-inference.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/00_ngame-for-msmarco-inference.ipynb 3
import os
# os.environ['CUDA_VISIBLE_DEVICES'] = "2,3"

import argparse, json
from tqdm.auto import tqdm

from xcai.misc import *
from xcai.main import *
from xcai.basics import *

# %% ../nbs/00_ngame-for-msmarco-inference.ipynb 5
os.environ['WANDB_PROJECT'] = "01_upma-msmarco-gpt-concept-substring-linker"

# %% ../nbs/00_ngame-for-msmarco-inference.ipynb 20
if __name__ == '__main__':
    output_dir = "/data/outputs/upma/07_msmarco-gpt-intent-substring-linker-with-ngame-loss-001"

    input_args = parse_args()
    extra_args = additional_args()

    input_args.use_sxc_sampler = True
    input_args.pickle_dir = "/home/aiscuser/scratch1/datasets/processed/"
    mname = "sentence-transformers/msmarco-distilbert-cos-v5"

    if input_args.beir_mode:
        if extra_args.use_task_specific_metadata:
            meta_file = "document_substring/raw_data/sq-substring.raw.csv"
            save_file_name = "document-substring_sq-substring"
            pred_dir_name = "cross_predictions/document-substring_sq-substring"
        else:
            meta_dir = "intent_substring/raw_data/"
            meta_file = f"{meta_dir}/all-intent.raw.csv" if extra_args.use_all else f"{meta_dir}/intent.raw.csv"
            save_file_name = "msmarco-all-intent-substring" if extra_args.use_all else "msmarco-intent-substring" 
            pred_dir_name = "cross_predictions/all-intent" if extra_args.use_all else "predictions"

        linker_beir_inference(output_dir, input_args, mname, save_file_name=save_file_name, meta_file=meta_file, 
                              pred_dir_name=pred_dir_name, use_task_specific_metadata=extra_args.use_task_specific_metadata, 
                              datasets=DATASETS)
    else:
        if extra_args.use_all:
            config_file = "/data/datasets/beir/msmarco/XC/configs/data_gpt-all-intent-substring.json"
            assert input_args.do_test_inference, f"All substrings should be used in inference mode"

            input_args.prediction_suffix = "all-intent"
        else:
            config_file = "/data/datasets/beir/msmarco/XC/configs/data_gpt-intent-substring.json"
        train_dset, test_dset = load_linker_block("msmarco", config_file, input_args, extra_args)
        linker_run(output_dir, input_args, mname, test_dset, train_dset)

