# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_ngame-for-msmarco-inference.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/00_ngame-for-msmarco-inference.ipynb 3
import os, argparse, json, scipy.sparse as sp

from tqdm.auto import tqdm
from typing import Optional, List

from xcai.misc import *
from xcai.main import *
from xcai.basics import *

from xcai.sdata import SMainXCDataset, SXCDataset

# %% ../nbs/00_ngame-for-msmarco-inference.ipynb 5
os.environ['WANDB_PROJECT'] = "01_upma-msmarco-gpt-concept-substring-linker"

DATASETS = [
    "trecdl19",
    "trecdl20",
]

MULTIHOP_DATASETS = [
    "musique",
]

def linker_multihop_inference(output_dir:str, input_args:argparse.ArgumentParser, mname:str, save_file_name:str, 
                              meta_file:str, pred_meta_file:Optional[str]=None, datasets:Optional[List]=None, 
                              pred_dir_name:Optional[str]=None, use_task_specific_metadata:Optional[bool]=False, 
                              meta_sequence_length:Optional[int]=64, get_data_predictions:Optional[bool]=True, 
                              get_label_predictions:Optional[bool]=False, get_meta_predictions:Optional[bool]=False, 
                              normalize:Optional[bool]=True, use_layer_norm:Optional[bool]=True, eval_batch_size:Optional[int]=800, 
                              model_type:Optional[str]="best"):
    
    input_args.only_test = True
    
    os.makedirs(f"{input_args.pickle_dir}/multihop/", exist_ok=True)

    meta_info = load_info(f"{input_args.pickle_dir}/{save_file_name}.joblib", f"/data/datasets/beir/msmarco/XC/{meta_file}",
                          mname, sequence_length=meta_sequence_length)

    datasets = MULTIHOP_DATASETS if datasets is None else datasets
    for dataset in tqdm(datasets):
        print(dataset)
        dataset_prefix = dataset.replace("/", "-")

        # load data
        input_args.do_test_inference = input_args.save_test_prediction = True
        test_info = load_info(f"{input_args.pickle_dir}/multihop/{dataset_prefix}.joblib",
                              f"/data/datasets/multihop/{dataset}/XC/raw_data/test.raw.csv",
                              mname, sequence_length=32)
        test_dset = SXCDataset(SMainXCDataset(data_info=test_info, lbl_info=meta_info))

        input_args.prediction_suffix = dataset_prefix
        trn_repr, tst_repr, lbl_repr, trn_pred, tst_pred, trn_metric, tst_metric = linker_run(output_dir, input_args, 
                                                                                              mname, test_dset, 
                                                                                              save_dir_name=pred_dir_name, 
                                                                                              normalize=normalize, 
                                                                                              use_layer_norm=use_layer_norm, 
                                                                                              eval_batch_size=eval_batch_size, 
                                                                                              model_type=model_type)
        print(tst_metric)


def additional_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('--multihop_mode', action='store_true')
    return parser.parse_known_args()[0]


# %% ../nbs/00_ngame-for-msmarco-inference.ipynb 20
if __name__ == '__main__':
    # output_dir = "/data/outputs/upma/07_msmarco-gpt-intent-substring-linker-with-ngame-loss-002"
    output_dir = "/home/sasokan/b-sprabhu/outputs/upma/07_msmarco-gpt-intent-substring-linker-with-ngame-loss-002"

    input_args = parse_args()
    extra_args = additional_args()

    input_args.use_sxc_sampler = True
    # input_args.pickle_dir = "/home/aiscuser/scratch1/datasets/processed/"
    input_args.pickle_dir = "/data/suchith/datasets/processed/"

    mname = "sentence-transformers/msmarco-distilbert-cos-v5"

    if input_args.beir_mode:
        meta_dir, save_file_name, pred_dir_name = "intent_substring/conflation_01/raw_data/", "msmarco-intent-substring-conflation-01", "predictions"
        meta_file = f"{meta_dir}/intent.raw.csv"

        # linker_beir_inference(output_dir, input_args, mname, save_file_name=save_file_name, meta_file=meta_file, 
        #                       pred_dir_name=pred_dir_name, meta_sequence_length=128, get_label_predictions=True, datasets=DATASETS)

        linker_beir_inference(output_dir, input_args, mname, save_file_name=save_file_name, meta_file=meta_file, 
                              pred_dir_name=pred_dir_name, meta_sequence_length=128, datasets=DATASETS)

    elif extra_args.multihop_mode:
        meta_dir, save_file_name, pred_dir_name = "intent_substring/conflation_01/raw_data/", "msmarco-intent-substring-conflation-01", "predictions"
        meta_file = f"{meta_dir}/intent.raw.csv"

        linker_multihop_inference(output_dir, input_args, mname, save_file_name=save_file_name, meta_file=meta_file, 
                                  pred_dir_name=pred_dir_name, meta_sequence_length=128)

    elif input_args.beir_metadata_mapping:
        meta_file, save_file_name = "intent_substring/conflation_01/raw_data/intent.raw.csv", "msmarco-intent-substring-conflation-01"
        pred_meta_file = "document_intent_substring/simple/raw_data/label_intent.raw.csv" 

        linker_beir_inference(output_dir, input_args, mname, save_file_name=save_file_name, meta_file=meta_file, pred_meta_file=pred_meta_file, 
                              meta_sequence_length=128, get_data_predictions=False, get_meta_predictions=True)
    else:
        config_file = "/data/datasets/beir/msmarco/XC/configs/data_gpt-intent-substring-conflation-01.json"
        train_dset, test_dset = load_linker_block("msmarco", config_file, input_args, extra_args)

        # lbl_intent = sp.load_npz("/data/datasets/beir/msmarco/XC/intent_substring/conflation_01/intent_lbl_X_Y.npz")
        # lbl_file = "/data/datasets/beir/msmarco/XC//raw_data/label.raw.txt"
        # lbl_info = load_info(f"{input_args.pickle_dir}/beir/msmarco-label.joblib", lbl_file, mname, sequence_length=128)
        # label_dset = SXCDataset(SMainXCDataset(data_info=lbl_info, data_lbl=lbl_intent, lbl_info=test_dset.data.lbl_info))
        label_dset = None

        linker_run(output_dir, input_args, mname, test_dset, train_dset, label_dset=label_dset)

