# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_ngame-for-msmarco-inference.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/00_ngame-for-msmarco-inference.ipynb 3
import os, argparse, json, scipy.sparse as sp

from tqdm.auto import tqdm

from xcai.misc import *
from xcai.main import *
from xcai.basics import *

from xcai.sdata import SMainXCDataset, SXCDataset

# %% ../nbs/00_ngame-for-msmarco-inference.ipynb 5
os.environ['WANDB_PROJECT'] = "01_upma-msmarco-gpt-concept-substring-linker"

DATASETS = [
    "climate-fever",
    "dbpedia-entity",
    "fever",
    "fiqa",
    "hotpotqa",
    "nfcorpus",
    "nq",
    "quora",
    "scidocs",
    "scifact",
    "webis-touche2020",
    "trec-covid",
    "cqadupstack/android",
    "cqadupstack/english",
    "cqadupstack/gaming",
    "cqadupstack/gis",
    "cqadupstack/mathematica",
    "cqadupstack/physics",
    "cqadupstack/programmers",
    "cqadupstack/stats",
    "cqadupstack/tex",
    "cqadupstack/unix",
    "cqadupstack/webmasters",
    "cqadupstack/wordpress"
]

# %% ../nbs/00_ngame-for-msmarco-inference.ipynb 20
if __name__ == '__main__':
    output_dir = "/data/outputs/upma/07_msmarco-gpt-intent-substring-linker-with-ngame-loss-002"

    input_args = parse_args()
    extra_args = additional_args()

    input_args.use_sxc_sampler = True
    input_args.pickle_dir = "/home/aiscuser/scratch1/datasets/processed/"
    mname = "sentence-transformers/msmarco-distilbert-cos-v5"

    if input_args.beir_mode:
        meta_dir, save_file_name, pred_dir_name = "intent_substring/conflation_01/raw_data/", "msmarco-intent-substring-conflation-01", "predictions"
        meta_file = f"{meta_dir}/intent.raw.csv"

        linker_beir_inference(output_dir, input_args, mname, save_file_name=save_file_name, meta_file=meta_file, 
                              pred_dir_name=pred_dir_name, meta_sequence_length=128, get_label_predictions=True, datasets=DATASETS)
    else:
        config_file = "/data/datasets/beir/msmarco/XC/configs/data_gpt-intent-substring-conflation-01.json"

        train_dset, test_dset = load_linker_block("msmarco", config_file, input_args, extra_args)

        # lbl_intent = sp.load_npz("/data/datasets/beir/msmarco/XC/intent_substring/conflation_01/intent_lbl_X_Y.npz")
        # lbl_file = "/data/datasets/beir/msmarco/XC//raw_data/label.raw.txt"
        # lbl_info = load_info(f"{input_args.pickle_dir}/beir/msmarco-label.joblib", lbl_file, mname, sequence_length=128)
        # label_dset = SXCDataset(SMainXCDataset(data_info=lbl_info, data_lbl=lbl_intent, lbl_info=test_dset.data.lbl_info))
        label_dset = None

        linker_run(output_dir, input_args, mname, test_dset, train_dset, label_dset=label_dset, normalize=False)

