# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/37_training-msmarco-distilbert-from-scratch.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/37_training-msmarco-distilbert-from-scratch.ipynb 2
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "0,1"

import torch,json, torch.multiprocessing as mp, joblib, numpy as np, scipy.sparse as sp, argparse
from typing import Optional, Union, Callable

from xcai.basics import *
from xcai.misc import *
from xcai.main import *

# %% ../nbs/37_training-msmarco-distilbert-from-scratch.ipynb 4
os.environ["WANDB_PROJECT"] = "02_upma-msmarco-gpt-concept-substring"

# %% ../nbs/37_training-msmarco-distilbert-from-scratch.ipynb 21
if __name__ == '__main__':
    input_args = parse_args()

    output_dir = "/home/aiscuser/scratch1/outputs/upma/08_upma-with-ngame-gpt-narrow-substring-linker-for-msmarco-001"

    input_args.use_sxc_sampler = True
    input_args.pickle_dir = "/home/aiscuser/scratch1/datasets/processed/"
    mname = "distilbert-base-uncased"

    if input_args.beir_mode:
        meta_file = "/data/datasets/beir/msmarco/XC/narrow_substring/raw_data/substring.raw.csv"
        linker_dir = "06_msmarco-gpt-narrow-substring-linker-with-ngame-loss-001"
        upma_beir_inference(output_dir, input_args, mname, "msmarco-narrow-substring", meta_file, linker_dir)
    else:
        config_file = (
            "configs/msmarco/narrow_substring/data_lbl_ngame-gpt-narrow-substring_ce-negatives-topk-05-linker_exact.json"
            if input_args.exact else
            "configs/msmarco/narrow_substring/data_lbl_ngame-gpt-narrow-substring.json"
        )
        train_dset, test_dset = load_upma_block("msmarco", config_file, input_args)
        upma_run(output_dir, input_args, mname, test_dset, train_dset)

