# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/37_training-msmarco-distilbert-from-scratch.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/37_training-msmarco-distilbert-from-scratch.ipynb 2
import os
# os.environ["CUDA_VISIBLE_DEVICES"] = "2,3"

import torch,json, torch.multiprocessing as mp, joblib, numpy as np, scipy.sparse as sp, argparse

from xcai.misc import *
from xcai.basics import *

# %% ../nbs/37_training-msmarco-distilbert-from-scratch.ipynb 4
os.environ["WANDB_PROJECT"] = "02_upma-msmarco-gpt-concept-substring"

# %% ../nbs/37_training-msmarco-distilbert-from-scratch.ipynb 21
if __name__ == '__main__':
    input_args = parse_args()

    output_dir = "/data/outputs/upma/09_upma-with-ngame-gpt-intent-substring-linker-for-msmarco-010"

    input_args.use_sxc_sampler = True
    input_args.pickle_dir = "/home/aiscuser/scratch1/datasets/processed/"
    mname = "distilbert-base-uncased"

    memory_injection_layer = 4

    if input_args.beir_mode:
        meta_file = "/data/datasets/beir/msmarco/XC/intent_substring/conflation_01/raw_data/intent.raw.csv"
        linker_dir = "/data/outputs/upma/07_msmarco-gpt-intent-substring-linker-with-ngame-loss-002/"
        upma_beir_inference(output_dir, input_args, mname, "msmarco-intent-substring-conflation-01", meta_file, linker_dir, eval_batch_size=400, 
                            data_repr_pooling=False, memory_injection_layer=memory_injection_layer)
    else:
        config_file = (
            "configs/msmarco/intent_substring/data_lbl_ngame-gpt-intent-substring-conflation-01_ce-negatives-topk-05-linker-07-msmarco-gpt-intent-substring-linker-with-ngame-loss-003-002_exact.json"
            if input_args.exact else
            "configs/msmarco/intent_substring/data_lbl_ngame-gpt-intent-substring-conflation-01.json"
        )
        train_dset, test_dset = load_upma_block("msmarco", config_file, input_args)
        upma_run(output_dir, input_args, mname, test_dset, train_dset, train_batch_size=128, data_repr_pooling=False, 
                 memory_injection_layer=memory_injection_layer)

