# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_ngame-for-msmarco-inference.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/00_ngame-for-msmarco-inference.ipynb 3
import os
os.environ['CUDA_VISIBLE_DEVICES'] = "2,3"

import torch,json, torch.multiprocessing as mp, joblib, numpy as np, scipy.sparse as sp, argparse

from xcai.misc import *
from xcai.basics import *

# %% ../nbs/00_ngame-for-msmarco-inference.ipynb 5
os.environ["WANDB_PROJECT"] = "02_upma-msmarco-gpt-concept-substring"

# %% ../nbs/00_ngame-for-msmarco-inference.ipynb 20
if __name__ == '__main__':
    input_args = parse_args()

    output_dir = "/data/outputs/upma/11_early-fusion-with-ngame-gpt-intent-substring-linker-for-msmarco-001"

    input_args.use_sxc_sampler = True
    input_args.pickle_dir = "/home/aiscuser/scratch1/datasets/processed/"
    mname = "distilbert-base-uncased"

    if input_args.beir_mode:
        early_fusion_beir_inference(output_dir, input_args, mname, "07_msmarco-gpt-intent-substring-linker-with-ngame-loss-001")
    else:
        config_file = (
            "configs/msmarco/intent_substring/data-ngame-gpt-intent-substring_lbl_ce-negatives-topk-05-linker_exact.json"
            if input_args.exact else
            "configs/msmarco/intent_substring/data-ngame-gpt-intent-substring_lbl.json"
        )
        train_dset, test_dset = load_early_fusion_block("msmarco", config_file, input_args)
        early_fusion_run(output_dir, input_args, mname, test_dset, train_dset)

