# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_ngame-for-msmarco-inference.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/00_ngame-for-msmarco-inference.ipynb 3
import os
# os.environ['CUDA_VISIBLE_DEVICES'] = "2,3"

import argparse, json
from tqdm.auto import tqdm

from xcai.misc import *
from xcai.main import *
from xcai.basics import *

# %% ../nbs/00_ngame-for-msmarco-inference.ipynb 5
os.environ["WANDB_PROJECT"] = "03_upma-beir-gpt-concept-substring-linker"

DATASETS = [
    "arguana",
    "msmarco",
    "climate-fever",
    "dbpedia-entity",
    "fever",
    "fiqa",
    "hotpotqa",
    "nfcorpus",
    "nq",
    # "quora",
    "scidocs",
    "scifact",
    "webis-touche2020",
    "trec-covid",
    "cqadupstack/android",
    "cqadupstack/english",
    "cqadupstack/gaming",
    "cqadupstack/gis",
    "cqadupstack/mathematica",
    "cqadupstack/physics",
    "cqadupstack/programmers",
    "cqadupstack/stats",
    "cqadupstack/tex",
    "cqadupstack/unix",
    "cqadupstack/webmasters",
    "cqadupstack/wordpress"
]

# %% ../nbs/00_ngame-for-msmarco-inference.ipynb 20
if __name__ == '__main__':
    output_dir = "/data/outputs/upma/12_beir-gpt-intent-substring-document-linker-with-ngame-loss-001/"

    input_args = parse_args()
    extra_args = additional_args()

    input_args.use_sxc_sampler = True
    input_args.pickle_dir = "/home/aiscuser/scratch1/datasets/processed/"
    mname = "sentence-transformers/msmarco-distilbert-cos-v5"

    if input_args.beir_mode:
        meta_file = "document_intent_substring/simple/raw_data/label_intent.raw.csv"
        save_file_name = "document-intent-substring_simple"
        pred_dir_name = "cross_predictions/document-intent-substring_simple"

        input_args.label_similarity = True

        linker_beir_inference(output_dir, input_args, mname, save_file_name=save_file_name, meta_file=meta_file, 
                              pred_dir_name=pred_dir_name, use_task_specific_metadata=True, datasets=DATASETS)
    else:
        config_file = "/data/datasets/beir/experiments/00_beir-gpt-document-intent-substring/configs/label_gpt-document-intent-substring.json"

        train_dset, test_dset = load_linker_block("beir-gpt-document-intent-substring", config_file, input_args, extra_args)
        linker_run(output_dir, input_args, mname, test_dset, train_dset)

