# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_ngame-for-msmarco-inference.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/00_ngame-for-msmarco-inference.ipynb 3
import os
# os.environ['CUDA_VISIBLE_DEVICES'] = "2,3"

import argparse, json
from tqdm.auto import tqdm

from xcai.misc import *
from xcai.main import *
from xcai.basics import *

# %% ../nbs/00_ngame-for-msmarco-inference.ipynb 5
os.environ["WANDB_PROJECT"] = "01_upma-msmarco-gpt-concept-substring-linker"

# %% ../nbs/00_ngame-for-msmarco-inference.ipynb 20
if __name__ == '__main__':
    output_dir = "/home/aiscuser/scratch1/outputs/upma/12_beir-gpt-intent-substring-document-linker-with-ngame-loss-001/"

    input_args = parse_args()
    extra_args = additional_args()

    input_args.use_sxc_sampler = True
    input_args.pickle_dir = "/home/aiscuser/scratch1/datasets/processed/"
    mname = "sentence-transformers/msmarco-distilbert-cos-v5"

    if input_args.beir_mode:
        raise NotImplementedError("BeIR inference must be implemented.")
    else:
        config_file = "/data/datasets/beir/experiments/00_beir-gpt-document-intent-substring/configs/label_gpt-document-intent-substring.json"

        train_dset, test_dset = load_linker_block("beir-gpt-document-intent-substring", config_file, input_args, extra_args)
        linker_run(output_dir, input_args, mname, test_dset, train_dset)

