# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/37_training-msmarco-distilbert-from-scratch.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/37_training-msmarco-distilbert-from-scratch.ipynb 2
import os, torch, json, torch.multiprocessing as mp, joblib, numpy as np, scipy.sparse as sp, argparse

from typing import Optional, Union, Callable, List
from tqdm.auto import tqdm

from xcai.misc import *
from xcai.basics import *
from xcai.models.upma import UPA000, UPMAConfig

# %% ../nbs/37_training-msmarco-distilbert-from-scratch.ipynb 4
os.environ["WANDB_PROJECT"] = "02_upma-msmarco-gpt-concept-substring"


def upma_run(output_dir:str, input_args:argparse.ArgumentParser, mname:str, test_dset:Union[XCDataset, SXCDataset],
             train_dset:Optional[Union[XCDataset, SXCDataset]]=None, collator:Optional[Callable]=identity_collate_fn, 
             train_batch_size:Optional[int]=128, eval_batch_size:Optional[int]=400, save_dir_name:Optional[str]=None,
             data_repr_pooling:Optional[bool]=True, memory_injection_layer:Optional[Union[int, List]]=6, 
             memory_type:Optional[Union[str, List]]="embeddings", n_memory_layers:Optional[int]=3, 
             use_label_memory:Optional[bool]=False, num_input_metadata:Optional[int]=5):

    label_names = ["plbl2data_idx", "plbl2data_data2ptr", "lnk2data_idx", "lnk2data_data2ptr", "lnk2data_scores"]
    if "encoder" in memory_type: label_names = label_names + ["lnk2data_input_ids", "lnk2data_attention_mask"]
    
    label_memory_names = ["lnk2lbl_idx", "lnk2lbl_data2ptr", "lnk2lbl_lbl2ptr", "lnk2lbl_scores", 
                          "lnk2neg_idx", "lnk2neg_data2ptr", "lnk2neg_neg2ptr", "lnk2neg_scores"]
    if "encoder" in memory_type:
        label_memory_names = label_memory_names + ["lnk2lbl_input_ids", "lnk2lbl_attention_mask", "lnk2neg_input_ids", "lnk2neg_attention_mask"]
    
    label_names = label_names + label_memory_names if use_label_memory else label_names
    use_label_metadata = lbl2data_inject_memory = neg2data_inject_memory = use_label_memory

    memory_type = memory_type if isinstance(memory_type, list) else [memory_type]
    memory_injection_layer = memory_injection_layer if isinstance(memory_injection_layer, list) else [memory_injection_layer]
    
    args = XCLearningArguments(
        output_dir=output_dir,
        logging_first_step=True,
        per_device_train_batch_size=train_batch_size,
        per_device_eval_batch_size=eval_batch_size,
        representation_num_beams=200,
        representation_accumulation_steps=10,
        save_strategy="steps",
        eval_strategy="steps",
        eval_steps=5000,
        save_steps=5000,
        save_total_limit=5,
        num_train_epochs=50,
        predict_with_representation=True,
        representation_search_type='BRUTEFORCE',
        search_normalize=False,

        adam_epsilon=1e-6,
        warmup_steps=1000,
        weight_decay=0.01,
        learning_rate=6e-5,
        label_names=label_names,

        group_by_cluster=True,
        use_data_metadata_for_clustering=True,
        num_clustering_warmup_epochs=10,
        num_cluster_update_epochs=5,
        num_cluster_size_update_epochs=25,
        clustering_type='EXPO',
        minimum_cluster_size=2,
        maximum_cluster_size=1600,

        data_aug_meta_name="lnk",
        use_label_metadata=use_label_metadata,

        metric_for_best_model='N@10',
        load_best_model_at_end=True,
        target_indices_key='plbl2data_idx',
        target_pointer_key='plbl2data_data2ptr',

        use_encoder_parallel=True,
        max_grad_norm=None,
        fp16=True,

        use_cpu_for_searching=True,
        use_cpu_for_clustering=True,
    )

    config = UPMAConfig(
        memory_module_names = memory_type,
        memory_injection_layers = memory_injection_layer,

        num_total_metadata = test_dset.meta["lnk_meta"].n_meta,
        num_input_metadata = num_input_metadata,
        metadata_dropout = 0.1,

        n_memory_layers = n_memory_layers,

        data_aug_meta_prefix="lnk2data",
        lbl2data_aug_meta_prefix="lnk2lbl",
        neg2data_aug_meta_prefix="lnk2neg",

        data_inject_memory=True,
        lbl2data_inject_memory=lbl2data_inject_memory,
        neg2data_inject_memory=neg2data_inject_memory,

        data_repr_pooling=data_repr_pooling,
        data_normalize=False,

        margin=0.3,
        num_negatives=10,
        tau=0.1,
        apply_softmax=True,
        reduction="mean",

        calib_margin=0.3,
        calib_num_negatives=10,
        calib_tau=0.1,
        calib_apply_softmax=False,

        calib_loss_weight=0.1,
        use_calib_loss=True,

        use_encoder_parallel=True,
        loss_function="margin",

        initialize_memory_embeddings_from_injection_layer_mean=True,
        metadata_embedding_file=f"{output_dir}/metadata/gpt-substring.pth",
    )

    def model_fn(mname:Optional[str]=None):
        meta_dset = test_dset.meta_dset("lnk_meta")
        model = UPA000.from_pretrained(config, mname=mname, meta_dset=meta_dset, batch_size=1000)
        return model

    def init_fn(model):
        with torch.no_grad():
            meta_embeds = torch.load("/data/outputs/upma/07_msmarco-gpt-intent-substring-linker-with-ngame-loss-002/predictions/label_repr.pth")
            meta_embeds = torch.vstack([meta_embeds, torch.zeros((1,768))])
            model.encoder.memory_modules[0].set_metadata_embeddings(meta_embeds)
            model.encoder.memory_modules[0].metadata_embeddings.weight.requires_grad_(False)

    metric = PrecReclMrr(test_dset.n_lbl, test_dset.data.data_lbl_filterer, pk=10, rk=200, rep_pk=[1, 3, 5, 10],
                         rep_rk=[10, 100, 200], mk=[5, 10, 20])

    model = load_model(args.output_dir, model_fn, init_fn=init_fn, do_inference=check_inference_mode(input_args), 
                       use_pretrained=input_args.use_pretrained)

    learn = XCLearner(
        model=model,
        args=args,
        train_dataset=train_dset,
        eval_dataset=test_dset,
        data_collator=collator,
        compute_metrics=metric,
    )

    return main(learn, input_args, n_lbl=test_dset.n_lbl, save_dir_name=save_dir_name)


# %% ../nbs/37_training-msmarco-distilbert-from-scratch.ipynb 21
if __name__ == '__main__':
    input_args = parse_args()

    output_dir = "/home/aiscuser/scratch1/outputs/upma/16_upma-with-ngame-gpt-intent-substring-linker-for-msmarco-and-frozen-linker-metadata-embeddings-001"

    input_args.use_sxc_sampler = True
    input_args.pickle_dir = "/home/aiscuser/scratch1/datasets/processed/"
    mname = "distilbert-base-uncased"

    memory_injection_layer = 1

    if input_args.beir_mode:
        meta_file = "/data/datasets/beir/msmarco/XC/intent_substring/conflation_01/raw_data/intent.raw.csv"
        linker_dir = "/data/outputs/upma/07_msmarco-gpt-intent-substring-linker-with-ngame-loss-002/"
        upma_beir_inference(output_dir, input_args, mname, "msmarco-intent-substring-conflation-01", meta_file, linker_dir, eval_batch_size=400, 
                            data_repr_pooling=False, memory_injection_layer=memory_injection_layer, data_lnk_topk=5, n_data_lnk_samples=5)
    else:
        config_file = (
            "configs/msmarco/intent_substring/data_lbl_ngame-gpt-intent-substring-conflation-01_ce-negatives-topk-05-linker_exact.json"
            if input_args.exact else
            "configs/msmarco/intent_substring/data_lbl_ngame-gpt-intent-substring-conflation-01.json"
        )
        train_dset, test_dset = load_upma_block("msmarco", config_file, input_args)
        upma_run(output_dir, input_args, mname, test_dset, train_dset, train_batch_size=128, data_repr_pooling=False, 
                 memory_injection_layer=memory_injection_layer)

