# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/37_training-msmarco-distilbert-from-scratch.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/37_training-msmarco-distilbert-from-scratch.ipynb 2
import os, torch, json, torch.multiprocessing as mp, joblib, numpy as np, scipy.sparse as sp, argparse

from xcai.misc import *
from xcai.basics import *

# %% ../nbs/37_training-msmarco-distilbert-from-scratch.ipynb 4
os.environ["WANDB_PROJECT"] = "02_upma-msmarco-gpt-concept-substring"

# start analysis

from tqdm.auto import tqdm
from typing import Optional, List, Union
from xclib.utils.sparse import retain_topk
from xcai.sdata import SXCDataset, SMetaXCDataset


def get_shuffled_matrix(data_meta, seed=100):
    np.random.seed(seed)
    data_meta = data_meta.copy()
    rnd_idx = np.random.permutation(data_meta.shape[0])
    data_meta = data_meta[rnd_idx]
    return data_meta


def insert_shuffled_meta_items(dset, seed=100):
    data_meta = get_shuffled_matrix(dset.meta["lnk_meta"].data_meta, seed=seed)
    dset.meta["lnk_meta"].update_meta_matrix(data_meta)


def get_random_matrix(n_data:int, n_meta:int, num_meta:Optional[int]=5, seed:Optional[int]=100):
    np.random.seed(seed)
    data, indices, indptr = [], [], [0]
    for _ in range(n_data):
        data.extend(np.random.random(num_meta))
        indices.extend(np.random.choice(n_meta, size=num_meta))
        indptr.append(len(data))

    data_meta = sp.csr_matrix((data, indices, indptr), shape=(len(indptr)-1, n_meta))
    data_meta.sort_indices()
    return data_meta


def insert_random_meta_items(dset, num_meta=5, seed=100):
    n_data, n_meta = dset.data.n_data, dset.meta["lnk_meta"].n_meta
    data_meta = get_random_matrix(n_data, n_meta, num_meta=num_meta, seed=seed)
    dset.meta["lnk_meta"].update_meta_matrix(data_meta)


def get_constant_matrix(data_meta):
    data_meta = data_meta.copy()
    data_meta.indices[:] = 0
    data_meta.sum_duplicates()
    data_meta.data[:] = 1.0
    return data_meta


def insert_constant_meta_items(dset):
    data_meta = get_constant_matrix(dset.meta["lnk_meta"].data_meta)
    dset.meta["lnk_meta"].update_meta_matrix(data_meta)


def upma_beir_inference(output_dir:str, input_args:argparse.ArgumentParser, mname:str, meta_save_fname:str, 
                        meta_file:str, linker_dir:str, data_dir:Optional[str]=None, n_data_lnk_samples:Optional[int]=5, n_lbl_lnk_samples:Optional[int]=5, 
                        data_lnk_topk:Optional[int]=5, lbl_lnk_topk:Optional[int]=5, eval_batch_size:Optional[int]=400, 
                        datasets:Optional[List]=None, data_repr_pooling:Optional[bool]=True, memory_injection_layer:Optional[Union[int, List]]=6, 
                        memory_type:Optional[Union[str, List]]="embeddings", n_memory_layers:Optional[int]=3, use_data_memory:Optional[bool]=True,
                        use_label_memory:Optional[bool]=False, num_input_metadata:Optional[int]=5, use_calib_loss:Optional[bool]=False, 
                        calib_loss_weight:Optional[float]=0.1, metric_dir_name:Optional[str]="metrics", pred_dir_name:Optional[str]=None, 
                        update_config_during_inference:Optional[bool]=False, tie_memory_encoder_weights:Optional[bool]=False, 
                        exclude_module_from_tying:Optional[str]=None, analysis_type:Optional[str]=None):
    
    metric_dir = f"{output_dir}/{metric_dir_name}"
    os.makedirs(metric_dir, exist_ok=True)

    input_args.only_test = input_args.do_test_inference = input_args.save_test_prediction = True
    
    meta_info = load_info(f"{input_args.pickle_dir}/{meta_save_fname}.joblib", meta_file, mname, 
                          sequence_length=64)

    if data_dir is None: data_dir = "/data"
    
    datasets = BEIR_DATASETS if datasets is None else datasets
    for dataset in tqdm(datasets):
        print(dataset)

        config_file = f"{data_dir}/datasets/beir/{dataset}/XC/configs/data.json"
        train_dset, test_dset = load_upma_block(dataset, config_file, input_args)

        dataset = dataset.replace("/", "-")
        data_meta = retain_topk(sp.load_npz(f"{linker_dir}/test_predictions_{dataset}.npz"), k=data_lnk_topk)

        # start analysis

        if analysis_type == "random":
            data_meta, lbl_meta = get_random_matrix(data_meta.shape[0], data_meta.shape[1], num_meta=data_lnk_topk, seed=1000), None
        elif analysis_type == "constant":
            data_meta, lbl_meta = get_constant_matrix(data_meta), None
        elif analysis_type == "shuffle":
            data_meta, lbl_meta = get_shuffled_matrix(data_meta), None
        else:
            data_meta, lbl_meta = data_meta, None

        # end analysis

        meta_kwargs = {
            "lnk_meta": SMetaXCDataset(prefix="lnk", data_meta=data_meta, lbl_meta=lbl_meta, meta_info=meta_info, n_sdata_meta_samples=n_data_lnk_samples,
                                       n_slbl_meta_samples=n_lbl_lnk_samples, return_scores=True, meta_oversample=True),
        }
        
        test_dset = SXCDataset(test_dset.data, **meta_kwargs)

        input_args.prediction_suffix = dataset
        trn_repr, tst_repr, lbl_repr, trn_pred, tst_pred, trn_metric, tst_metric = upma_run(output_dir, input_args, mname, test_dset, train_dset, 
                                                                                            eval_batch_size=eval_batch_size, 
                                                                                            save_dir_name=pred_dir_name, 
                                                                                            data_repr_pooling=data_repr_pooling, 
                                                                                            memory_injection_layer=memory_injection_layer, 
                                                                                            use_data_memory=use_data_memory, 
                                                                                            use_label_memory=use_label_memory, 
                                                                                            memory_type=memory_type, 
                                                                                            n_memory_layers=n_memory_layers, 
                                                                                            num_input_metadata=num_input_metadata, 
                                                                                            use_calib_loss=use_calib_loss, 
                                                                                            calib_loss_weight=calib_loss_weight, 
                                                                                            update_config_during_inference=update_config_during_inference, 
                                                                                            tie_memory_encoder_weights=tie_memory_encoder_weights, 
                                                                                            exclude_module_from_tying=exclude_module_from_tying)
        
        with open(f"{metric_dir}/{dataset}.json", "w") as file:
            json.dump({dataset: tst_metric}, file, indent=4)

    collate_beir_metrics(metric_dir)


def additional_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('--analysis_type', type=str, default=None)
    return parser.parse_known_args()[0]

# end analysis

# %% ../nbs/37_training-msmarco-distilbert-from-scratch.ipynb 21
if __name__ == '__main__':
    input_args = parse_args()
    extra_args = additional_args()

    output_dir = "/home/sasokan/suchith/outputs/upma/20_upma-ngame-gpt-intent-substring-linker-with-tied-meta-encoder-for-msmarco-004"

    input_args.use_sxc_sampler = True
    input_args.pickle_dir = "/data/suchith/datasets/processed/"
    mname = "distilbert-base-uncased"

    n_memory_layers = memory_injection_layer = 3
    memory_type = "encoder"

    tie_memory_encoder_weights = True
    exclude_module_from_tying = None

    # start analysis

    extra_args.analysis_type = "constant"

    # end analysis

    if input_args.beir_mode:
        meta_file = "/home/sasokan/b-sprabhu/datasets/beir/msmarco/XC/intent_substring/conflation_01/raw_data/intent.raw.csv"
        linker_dir = "/home/sasokan/b-sprabhu/outputs/upma/07_msmarco-gpt-intent-substring-linker-with-ngame-loss-002/predictions/"
        data_dir = "/home/sasokan/b-sprabhu/"

        # start analysis

        analysis_type = extra_args.analysis_type 

        # end analysis

        upma_beir_inference(output_dir, input_args, mname, "msmarco-intent-substring-conflation-01", meta_file, linker_dir, data_dir, 
                            eval_batch_size=400, data_repr_pooling=False, memory_injection_layer=memory_injection_layer, memory_type=memory_type, 
                            n_memory_layers=n_memory_layers, tie_memory_encoder_weights=tie_memory_encoder_weights, 
                            exclude_module_from_tying=exclude_module_from_tying, analysis_type=analysis_type)
    else:
        config_file = (
            "configs/msmarco/intent_substring/data_lbl_ngame-gpt-intent-substring-conflation-01_ce-negatives-topk-05-linker_exact.json"
            if input_args.exact else
            "configs/msmarco/intent_substring/data_lbl_ngame-gpt-intent-substring-conflation-01.json"
        )
        train_dset, test_dset = load_upma_block("msmarco", config_file, input_args)

        # start analysis

        analysis_type = extra_args.analysis_type
        use_data_memory = False if extra_args.analysis_type == "no_memory" else True

        if analysis_type == "random":
            insert_random_meta_items(train_dset)
            insert_random_meta_items(test_dset)
        elif analysis_type == "constant":
            insert_constant_meta_items(train_dset)
            insert_constant_meta_items(test_dset)
        elif analysis_type == "shuffle":
            insert_shuffled_meta_items(train_dset)
            insert_shuffled_meta_items(test_dset)

        breakpoint()

        # end analysis

        upma_run(output_dir, input_args, mname, test_dset, train_dset, train_batch_size=128, data_repr_pooling=False, 
                 memory_injection_layer=memory_injection_layer, memory_type=memory_type, n_memory_layers=n_memory_layers, 
                 tie_memory_encoder_weights=tie_memory_encoder_weights, exclude_module_from_tying=exclude_module_from_tying, 
                 resume_from_checkpoint=False, use_data_memory=use_data_memory)

