# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/37_training-msmarco-distilbert-from-scratch.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/37_training-msmarco-distilbert-from-scratch.ipynb 2
import os, torch, json, torch.multiprocessing as mp, joblib, numpy as np, scipy.sparse as sp, argparse

from xcai.misc import *
from xcai.basics import *

# %% ../nbs/37_training-msmarco-distilbert-from-scratch.ipynb 4
os.environ["WANDB_PROJECT"] = "02_upma-msmarco-gpt-concept-substring"

from tqdm.auto import tqdm
from typing import Optional, List, Union
from xclib.utils.sparse import retain_topk
from xcai.sdata import SXCDataset, SMetaXCDataset

def upma_beir_inference(output_dir:str, input_args:argparse.ArgumentParser, mname:str, data_dir:Optional[str]=None, 
                        n_data_lnk_samples:Optional[int]=5, n_lbl_lnk_samples:Optional[int]=5, 
                        data_lnk_topk:Optional[int]=5, lbl_lnk_topk:Optional[int]=5, eval_batch_size:Optional[int]=400, 
                        datasets:Optional[List]=None, data_repr_pooling:Optional[bool]=True, memory_injection_layer:Optional[Union[int, List]]=6, 
                        memory_type:Optional[Union[str, List]]="embeddings", n_memory_layers:Optional[int]=3, use_data_memory:Optional[bool]=True,
                        use_label_memory:Optional[bool]=False, num_input_metadata:Optional[int]=5, use_calib_loss:Optional[bool]=False, 
                        calib_loss_weight:Optional[float]=0.1, metric_dir_name:Optional[str]="metrics", pred_dir_name:Optional[str]=None, 
                        update_config_during_inference:Optional[bool]=False, tie_memory_encoder_weights:Optional[bool]=False, 
                        exclude_module_from_tying:Optional[str]=None, analysis_type:Optional[str]=None):
    
    metric_dir = f"{output_dir}/{metric_dir_name}"
    os.makedirs(metric_dir, exist_ok=True)

    input_args.only_test = input_args.do_test_inference = input_args.save_test_prediction = True
    
    if data_dir is None: data_dir = "/data"
    
    datasets = BEIR_DATASETS if datasets is None else datasets
    for dataset in tqdm(datasets):
        print(dataset)

        config_file = f"{data_dir}/datasets/beir/{dataset}/XC/configs/data.json"
        train_dset, test_dset = load_upma_block(dataset, config_file, input_args)
        
        dset_tag = dataset.replace("/", "-")

        input_args.prediction_suffix = dset_tag 
        trn_repr, tst_repr, lbl_repr, trn_pred, tst_pred, trn_metric, tst_metric = upma_run(output_dir, input_args, mname, test_dset, train_dset, 
                                                                                            eval_batch_size=eval_batch_size, 
                                                                                            save_dir_name=pred_dir_name, 
                                                                                            data_repr_pooling=data_repr_pooling, 
                                                                                            memory_injection_layer=memory_injection_layer, 
                                                                                            use_data_memory=use_data_memory, 
                                                                                            use_label_memory=use_label_memory, 
                                                                                            memory_type=memory_type, 
                                                                                            n_memory_layers=n_memory_layers, 
                                                                                            num_input_metadata=num_input_metadata, 
                                                                                            use_calib_loss=use_calib_loss, 
                                                                                            calib_loss_weight=calib_loss_weight, 
                                                                                            update_config_during_inference=update_config_during_inference, 
                                                                                            tie_memory_encoder_weights=tie_memory_encoder_weights, 
                                                                                            exclude_module_from_tying=exclude_module_from_tying, 
                                                                                            dataset=dataset)
        
        with open(f"{metric_dir}/{dset_tag}.json", "w") as file:
            json.dump({dataset: tst_metric}, file, indent=4)

    collate_beir_metrics(metric_dir)

# %% ../nbs/37_training-msmarco-distilbert-from-scratch.ipynb 21
if __name__ == '__main__':
    input_args = parse_args()
    output_dir = "/home/sasokan/suchith/outputs/upma/20_upma-ngame-gpt-intent-substring-linker-with-tied-meta-encoder-for-msmarco-003"

    input_args.use_sxc_sampler = True
    input_args.pickle_dir = "/data/suchith/datasets/processed/"
    mname = "distilbert-base-uncased"

    use_data_memory = False

    if input_args.beir_mode:
        metric_dir_name, pred_dir_name = "cross_metrics/verify", "cross_predictions/verify"
        upma_beir_inference(output_dir, input_args, mname, eval_batch_size=400, metric_dir_name=metric_dir_name, pred_dir_name=pred_dir_name,
                            data_repr_pooling=False, use_data_memory=use_data_memory)

    else:
        config_file = (
            "configs/msmarco/intent_substring/data_lbl_ngame-gpt-intent-substring-conflation-01_ce-negatives-topk-05-linker_exact.json"
            if input_args.exact else
            "configs/msmarco/intent_substring/data_lbl_ngame-gpt-intent-substring-conflation-01.json"
        )
        train_dset, test_dset = load_upma_block("msmarco", config_file, input_args)

        upma_run(output_dir, input_args, mname, test_dset, train_dset, train_batch_size=128, data_repr_pooling=False, 
                 exclude_module_from_tying=exclude_module_from_tying, resume_from_checkpoint=False, use_data_memory=use_data_memory)

