# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_ngame-for-msmarco-inference.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/00_ngame-for-msmarco-inference.ipynb 3
import argparse, json, os
from tqdm.auto import tqdm

from xcai.misc import *
from xcai.main import *
from xcai.basics import *

# %% ../nbs/00_ngame-for-msmarco-inference.ipynb 5
os.environ["WANDB_PROJECT"] = "04_musique"

# %% ../nbs/00_ngame-for-msmarco-inference.ipynb 20
if __name__ == '__main__':
    output_dir = "/home/sasokan/suchith/outputs/upma/21_ngame-for-musique-001"

    input_args = parse_args()
    extra_args = additional_args()

    input_args.use_sxc_sampler = True
    input_args.pickle_dir = "/home/sasokan/suchith/datasets/processed/"
    mname = "sentence-transformers/msmarco-distilbert-cos-v5"

    config_file = "/home/sasokan/b-sprabhu/datasets/multihop/musique/XC/configs/data.json"

    train_dset, test_dset = load_linker_block("musique", config_file, input_args, extra_args)
    linker_run(output_dir, input_args, mname, test_dset, train_dset)

