# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_ngame-for-msmarco-inference.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/00_ngame-for-msmarco-inference.ipynb 3
import argparse, json, os
from tqdm.auto import tqdm

from typing import Optional

from xcai.misc import *
from xcai.main import *
from xcai.basics import *

from xcai.multihop import *
from xcai.models.PPP0XX import DBT024, DBTConfig

# %% ../nbs/00_ngame-for-msmarco-inference.ipynb 5
os.environ["WANDB_PROJECT"] = "04_musique"

def load_block(dataset:str, config_file:str, input_args:argparse.ArgumentParser, n_data_lnk_samples:Optional[int]=5, 
               n_lbl_lnk_samples:Optional[int]=5, data_neg_topk:Optional[int]=None, train_label_topk:Optional[int]=None, 
               num_label_samples:Optional[int]=1, num_neg_samples:Optional[int]=1):
    config_key, fname = get_config_key(config_file)
    pkl_file = get_pkl_file(input_args.pickle_dir, f"{dataset}_{fname}_distilbert-base-uncased", input_args.use_sxc_sampler,
                            input_args.exact, input_args.only_test)

    train_data_meta_topk = None if data_neg_topk is None else {"neg_meta": data_neg_topk}

    os.makedirs(os.path.dirname(pkl_file), exist_ok=True)
    block = build_block(pkl_file, config_file, input_args.use_sxc_sampler, config_key, do_build=input_args.build_block, 
                        only_test=input_args.only_test, main_oversample=True, meta_oversample=True, return_scores=False, 
                        train_data_meta_topk=train_data_meta_topk, n_slbl_samples=num_label_samples, 
                        n_sdata_meta_samples={"neg_meta": num_neg_samples}, n_slbl_meta_samples={"neg_meta": num_neg_samples}, 
                        n_sneg_meta_samples={"neg_meta": num_neg_samples})
    
    train_dset, test_dset = None if block.train is None else block.train.dset, block.test.dset

    return train_dset, test_dset

# %% ../nbs/00_ngame-for-msmarco-inference.ipynb 20
if __name__ == '__main__':
    output_dir = "/data/suchith/outputs/upma/21_ngame-for-musique-with-negatives-002"

    input_args = parse_args()
    extra_args = additional_args()

    input_args.use_sxc_sampler = True
    input_args.pickle_dir = "/data/suchith/datasets/processed/"
    mname = "sentence-transformers/msmarco-distilbert-cos-v5"

    config_file = "/home/sasokan/b-sprabhu/datasets/multihop/musique/XC/configs/data_lbl_negatives.json"

    train_dset, test_dset = load_block("musique", config_file, input_args, extra_args, num_neg_samples=30)

    args = XCLearningArguments(
        output_dir=output_dir,
        logging_first_step=True,
        per_device_train_batch_size=16,
        per_device_eval_batch_size=800,
        representation_num_beams=200,
        representation_accumulation_steps=10,
        save_strategy="steps",
        eval_strategy="steps",
        eval_steps=5000,
        save_steps=5000,
        save_total_limit=5,
        num_train_epochs=300,
        predict_with_representation=True,
        representation_search_type='BRUTEFORCE',
        adam_epsilon=1e-6,
        warmup_steps=100,
        weight_decay=0.01,
        learning_rate=2e-4,

        group_by_cluster=True,
        num_clustering_warmup_epochs=10,
        num_cluster_update_epochs=5,
        num_cluster_size_update_epochs=25,
        clustering_type='EXPO',
        minimum_cluster_size=2,
        maximum_cluster_size=1600,

        metric_for_best_model='N@10',
        load_best_model_at_end=True,
        target_indices_key='plbl2data_idx',
        target_pointer_key='plbl2data_data2ptr',

        use_encoder_parallel=True,
        max_grad_norm=None,
        fp16=True,

        use_cpu_for_searching=True,
        use_cpu_for_clustering=True,

        label_names=["data_input_text"],
        use_saved_representation_for_indexing=True,
    )

    config = DBTConfig(
        num_negatives = 10,
        tau = 1.0,
        reduction = "mean",

        normalize = True,
        use_layer_norm = True,

        use_encoder_parallel = True,
        loss_function = "ranking"
    )

    def model_fn(mname, config):
        return DBT024.from_pretrained(mname, config=config)

    do_inference = check_inference_mode(input_args)
    model = load_model(args.output_dir, model_fn, {"mname": mname, "config": config}, do_inference=do_inference,
                       use_pretrained=input_args.use_pretrained)

    metric = PrecReclHits(test_dset.data.n_lbl, test_dset.data.data_lbl_filterer, prop=None if train_dset is None else train_dset.data.data_lbl,
                          pk=10, rk=200, hk=10, rep_pk=[1, 3, 5, 10], rep_rk=[10, 100, 200], rep_hk=[1, 3, 5, 10])

    # learn = MultihopLearner(
    #     tokenizer=config_file,
    #     model=model,
    #     args=args,
    #     train_dataset=train_dset,
    #     eval_dataset=test_dset,
    #     data_collator=identity_collate_fn,
    #     compute_metrics=metric,
    # )
    # print(learn.evaluate(beam_size=10, num_hops=4, topk_per_hop=10))

    learn = XCLearner(
        model=model,
        args=args,
        train_dataset=train_dset,
        eval_dataset=test_dset,
        data_collator=identity_collate_fn,
        compute_metrics=metric,
    )
    main(learn, input_args, n_lbl=test_dset.data.n_lbl)


