# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/37_training-msmarco-distilbert-from-scratch.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/37_training-msmarco-distilbert-from-scratch.ipynb 2
import os, torch, json, torch.multiprocessing as mp, joblib, numpy as np, scipy.sparse as sp, argparse

from xcai.misc import *
from xcai.basics import *

from typing import Optional, List, Union
from tqdm.auto import tqdm
from xclib.utils.sparse import retain_topk

# %% ../nbs/37_training-msmarco-distilbert-from-scratch.ipynb 4
os.environ["WANDB_PROJECT"] = "02_upma-msmarco-gpt-concept-substring"

DATASETS = [
    "arguana",
    "scidocs",
    "scifact",
    "webis-touche2020",
    "trec-covid",
    "fiqa",
    "msmarco",
    "nfcorpus",
]

def upma_beir_inference(output_dir:str, input_args:argparse.ArgumentParser, mname:str, meta_save_fname:str, meta_file:str, linker_dir:str, data_dir:Optional[str]=None, 
                        n_data_lnk_samples:Optional[int]=5, n_lbl_lnk_samples:Optional[int]=5, data_lnk_topk:Optional[int]=5, lbl_lnk_topk:Optional[int]=5, 

                        eval_batch_size:Optional[int]=400, datasets:Optional[List]=None, data_repr_pooling:Optional[bool]=True, 

                        memory_injection_layer:Optional[Union[int, List]]=6, memory_type:Optional[Union[str, List]]="embeddings", n_memory_layers:Optional[int]=3, 
                        use_data_memory:Optional[bool]=True, use_label_memory:Optional[bool]=False, 

                        num_input_metadata:Optional[int]=5, use_calib_loss:Optional[bool]=False, calib_loss_weight:Optional[float]=0.1, metric_dir_name:Optional[str]="metrics", 
                        pred_dir_name:Optional[str]=None, update_config_during_inference:Optional[bool]=False, tie_memory_encoder_weights:Optional[bool]=False, 
                        exclude_module_from_tying:Optional[str]=None, normalize:Optional[bool]=False, use_saved_representation_for_indexing:Optional[bool]=False, 
                        load_model_type:Optional[str]="best"):

    metric_dir = f"{output_dir}/{metric_dir_name}"
    os.makedirs(metric_dir, exist_ok=True)

    input_args.only_test = input_args.do_test_inference = input_args.save_test_prediction = True
    
    if data_dir is None: data_dir = "/data"
    
    datasets = BEIR_DATASETS if datasets is None else datasets
    for dataset in tqdm(datasets):
        print(dataset)
        dset_tag = dataset.replace("/", "-")

        # load query

        config_file = f"{data_dir}/datasets/beir/{dataset}/XC/configs/data.json"
        train_dset, test_dset = load_upma_block(dset_tag, config_file, input_args)

        # load metadata

        meta_file = f"/data/datasets/beir/{dataset}/XC/raw_data/hipporag-fact.raw.csv"
        meta_info = load_info(f"{input_args.pickle_dir}/{meta_save_fname}-{dset_tag}.joblib", meta_file, mname, 
                              sequence_length=64)

        # load data_meta matrix

        data_meta = retain_topk(sp.load_npz(f"{linker_dir}/{dataset}/test_facts.npz"), k=data_lnk_topk)
        assert data_meta.shape[1] == len(meta_info["input_ids"])

        # Create dataset

        meta_kwargs = {
            "lnk_meta": SMetaXCDataset(prefix="lnk", data_meta=data_meta, meta_info=meta_info, n_sdata_meta_samples=n_data_lnk_samples,
                                       n_slbl_meta_samples=n_lbl_lnk_samples, return_scores=True, meta_oversample=True),
        }
        test_dset = SXCDataset(test_dset.data, **meta_kwargs)

        input_args.prediction_suffix = dset_tag
        prefix_for_saved_representation_for_indexing = "msmarco" if dataset in ["msmarco", "trecdl19", "trecdl20"] else dataset
        
        trn_repr, tst_repr, lbl_repr, trn_pred, tst_pred, trn_metric, tst_metric = upma_run(output_dir, input_args, mname, test_dset, train_dset, 
                                                                                            eval_batch_size=eval_batch_size, 
                                                                                            save_dir_name=pred_dir_name, 
                                                                                            data_repr_pooling=data_repr_pooling, 
                                                                                            memory_injection_layer=memory_injection_layer, 
                                                                                            use_data_memory=use_data_memory, 
                                                                                            use_label_memory=use_label_memory, 
                                                                                            memory_type=memory_type, 
                                                                                            n_memory_layers=n_memory_layers, 
                                                                                            num_input_metadata=num_input_metadata, 
                                                                                            use_calib_loss=use_calib_loss, 
                                                                                            calib_loss_weight=calib_loss_weight, 
                                                                                            update_config_during_inference=update_config_during_inference, 
                                                                                            tie_memory_encoder_weights=tie_memory_encoder_weights, 
                                                                                            exclude_module_from_tying=exclude_module_from_tying,
                                                                                            use_saved_representation_for_indexing=use_saved_representation_for_indexing,
                                                                                            prefix_for_saved_representation_for_indexing=prefix_for_saved_representation_for_indexing, 
                                                                                            normalize=normalize, dataset=dataset, load_model_type=load_model_type)
        
        with open(f"{metric_dir}/{dataset}.json", "w") as file:
            json.dump({dataset: tst_metric}, file, indent=4)

    collate_beir_metrics(metric_dir)


# %% ../nbs/37_training-msmarco-distilbert-from-scratch.ipynb 21
if __name__ == '__main__':
    input_args = parse_args()

    output_dir = "/data/suchith/outputs/upma/24_upma-meta-encoder-with-nvembed-hipporag-linker-for-msmarco-with-calibration-loss-001"

    input_args.use_sxc_sampler = True
    input_args.pickle_dir = "/data/suchith/datasets/processed/"
    mname = "distilbert-base-uncased"

    n_memory_layers = 3
    memory_type = "encoder"
    memory_injection_layer = 6


    if input_args.beir_mode:
        meta_file = "/data/datasets/beir/msmarco/XC/raw_data/hipporag-fact.raw.csv"

        linker_dir = "/data/outputs/maggi/00_nvembed-to-compute-msmarco-embeddings-002/predictions/beir/"
        update_config_during_inference, use_data_memory = False, True
        metric_dir_name, pred_dir_name = "metrics", "predictions"

        upma_beir_inference(output_dir, input_args, mname, "nvembed-hipporag-facts", meta_file, linker_dir, eval_batch_size=600, data_repr_pooling=False, 

                            memory_injection_layer=memory_injection_layer, memory_type=memory_type, n_memory_layers=n_memory_layers, 
                            use_data_memory=use_data_memory, 

                            use_calib_loss=True, calib_loss_weight=0.1, 

                            metric_dir_name=metric_dir_name, pred_dir_name=pred_dir_name, update_config_during_inference=update_config_during_inference, 

                            num_input_metadata=5, n_data_lnk_samples=5, data_lnk_topk=5, datasets=DATASETS)

    else:
        config_file = (
            "/home/sasokan/suchith/upma/configs/msmarco/hipporag/data_lbl_nvembed-hipporag-facts_ce-negatives-topk-05-linker_exact.json"
            if input_args.exact else
            "/home/sasokan/suchith/upma/configs/msmarco/hipporag/data_lbl_nvembed-hipporag-facts_ce-negatives-topk-05-linker.json"
        )

        train_dset, test_dset = load_upma_block("msmarco", config_file, input_args)

        upma_run(output_dir, input_args, mname, test_dset, train_dset, train_batch_size=128, data_repr_pooling=False, 
                 memory_injection_layer=memory_injection_layer, memory_type=memory_type, n_memory_layers=n_memory_layers, 
                 use_calib_loss=True, calib_loss_weight=0.1)

