# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_ngame-for-msmarco-inference.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/00_ngame-for-msmarco-inference.ipynb 3
import os, torch, json, torch.multiprocessing as mp, joblib, numpy as np, scipy.sparse as sp, argparse

from xcai.misc import *
from xcai.basics import *

# %% ../nbs/00_ngame-for-msmarco-inference.ipynb 5
os.environ["WANDB_PROJECT"] = "07_ef-msmarco-gpt5-category"

# %% ../nbs/00_ngame-for-msmarco-inference.ipynb 20
if __name__ == '__main__':
    input_args = parse_args()

    output_dir = "/data/suchith/outputs/upma/25_early-fusion-with-category-metadata-gpt5-linker-for-msmarco-002"

    input_args.use_sxc_sampler = True
    input_args.pickle_dir = "/data/suchith/datasets/processed/"
    mname = "distilbert-base-uncased"

    if input_args.beir_mode:
        pass

    else:
        config_file = "/data/datasets/beir/metadata/msmarco/configs/data-category-summary-gpt5-linker_lbl_ce-negatives-topk-05-linker_exact.json"

        train_dset, test_dset = load_early_fusion_block("msmarco", config_file, input_args)
        early_fusion_run(output_dir, input_args, mname, test_dset, train_dset)

