# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/37_training-msmarco-distilbert-from-scratch.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/37_training-msmarco-distilbert-from-scratch.ipynb 2
import os, torch, json, torch.multiprocessing as mp, joblib, numpy as np, scipy.sparse as sp, argparse
from typing import Optional, Union, Callable, List
from tqdm.auto import tqdm

from xcai.basics import *
from xcai.models.PPP0XX import DBT023, DBTConfig

from xcai.misc import *

# %% ../nbs/37_training-msmarco-distilbert-from-scratch.ipynb 4
os.environ["WANDB_PROJECT"] = "08_linker-msmarco-nvembed-hipporag-fact"

def linker_run(output_dir:str, input_args:argparse.ArgumentParser, mname:str, test_dset:Union[XCDataset, SXCDataset],
               train_dset:Optional[Union[XCDataset, SXCDataset]]=None, label_dset:Optional[Union[XCDataset, SXCDataset]]=None,
               meta_dset:Optional[Union[XCDataset, SXCDataset]]=None, collator:Optional[Callable]=identity_collate_fn, 
               save_dir_name:Optional[str]=None, normalize:Optional[bool]=True, use_layer_norm:Optional[bool]=True, 
               eval_batch_size:Optional[int]=800, model_type:Optional[str]="best"):

    args = XCLearningArguments(
        output_dir=output_dir,
        logging_first_step=True,
        per_device_train_batch_size=128,
        per_device_eval_batch_size=eval_batch_size,
        representation_num_beams=200,
        representation_accumulation_steps=10,
        save_strategy="steps",
        eval_strategy="steps",
        eval_steps=5000,
        save_steps=5000,
        save_total_limit=5,
        num_train_epochs=50,
        predict_with_representation=True,
        representation_search_type='BRUTEFORCE',
        search_normalize=False, 

        adam_epsilon=1e-6,
        warmup_steps=1000,
        weight_decay=0.01,
        learning_rate=6e-5,
        label_names=['plbl2data_idx', 'plbl2data_data2ptr', 'plbl2data_scores'],
    
        group_by_cluster=True,
        num_clustering_warmup_epochs=10,
        num_cluster_update_epochs=5,
        num_cluster_size_update_epochs=25,
        clustering_type='EXPO',
        minimum_cluster_size=2,
        maximum_cluster_size=1600,
    
        metric_for_best_model='NDCG@10',
        load_best_model_at_end=True,
        target_indices_key='plbl2data_idx',
        target_pointer_key='plbl2data_data2ptr',
    
        use_encoder_parallel=True,
        max_grad_norm=None,
        fp16=True,

        use_cpu_for_searching=True,
        use_cpu_for_clustering=True,
    )

    config = DBTConfig(
        normalize = True,
        use_layer_norm = False,
        use_encoder_parallel = True,
    )

    def model_fn(mname):
        model = DBT023.from_pretrained(mname, config=config) 
        return model
    
    tst_ids = test_dset.data.data_info["identifier"]
    lbl_ids = test_dset.data.lbl_info["identifier"]
    
    assert tst_ids is not None
    assert lbl_ids is not None

    do_inference = check_inference_mode(input_args)

    metric = None
    if test_dset is not None:
        metric = BeirMetric(test_dset.n_lbl, k_values=[1, 3, 5, 10], qry_ids=tst_ids, lbl_ids=lbl_ids)

    model = load_model(args.output_dir, model_fn, {"mname": mname}, do_inference=do_inference, 
                       use_pretrained=input_args.use_pretrained)

    eval_dataset = label_dset if test_dset is None else test_dset
    eval_dataset = meta_dset if eval_dataset is None else eval_dataset
    n_lbl = eval_dataset.data.n_lbl
    
    learn = XCLearner(
        model=model,
        args=args,
        train_dataset=train_dset,
        eval_dataset=eval_dataset,
        data_collator=collator,
        compute_metrics=metric,
    )

    eval_dataset = get_label_dataset(test_dset, mname, input_args) if input_args.label_similarity else None

    return main(learn, input_args, n_lbl=n_lbl, eval_dataset=eval_dataset, eval_k=10, 
                train_k=10, label_dataset=label_dset, label_k=10, meta_dataset=meta_dset, meta_k=10,
                save_dir_name=save_dir_name)


import xcai.misc as misc
misc.linker_run = linker_run

# %% ../nbs/37_training-msmarco-distilbert-from-scratch.ipynb 21
if __name__ == '__main__':
    output_dir = "/data/suchith/outputs/upma/28_distilbert-nvembed-hipporag-fact-linker-for-msmarco-002"

    input_args = parse_args()

    input_args.use_sxc_sampler = True
    input_args.pickle_dir = "/data/suchith/datasets/processed/"
    mname = "distilbert-base-uncased"

    if input_args.beir_mode:
        # meta_file = "raw_data/hipporag-fact.raw.csv"
        # pred_dir_name = "cross_predictions"
        # linker_beir_inference(output_dir, input_args, mname, save_file_name="hipporag-fact", pred_dir_name=pred_dir_name, 
        #                       meta_file=meta_file, use_task_specific_metadata=True, meta_sequence_length=64)

        meta_file = "/data/datasets/beir/hotpotqa/XC/raw_data/hipporag-fact.raw.csv"
        save_file_name, pred_dir_name = f"{input_args.pickle_dir}/beir/hipporag-fact/hotpotqa.joblib", "cross_predictions"
        input_args.prediction_suffix = "hotpotqa"
        datasets = ["climate-fever", "fever", "dbpedia-entity", "nq"]
        linker_beir_inference(output_dir, input_args, mname, save_file_name=save_file_name, pred_dir_name=pred_dir_name, 
                              meta_file=meta_file, use_task_specific_metadata=False, meta_sequence_length=64, datasets=datasets)

    else:
        config_file = "configs/msmarco/msmarco_data_nvembed-hipporag-fact_positives-topk-05.json"
        config_key, fname = get_config_key(config_file)
        pkl_file = get_pkl_file(input_args.pickle_dir, f"msmarco_{fname}_distilbert-base-uncased", input_args.use_sxc_sampler, 
                                input_args.exact, input_args.only_test)

        os.makedirs(os.path.dirname(pkl_file), exist_ok=True)
        block = build_block(pkl_file, config_file, input_args.use_sxc_sampler, config_key, do_build=input_args.build_block, 
                            only_test=input_args.only_test, main_oversample=True, meta_oversample=True, return_scores=True, 
                            n_slbl_samples=1, n_sdata_meta_samples=1)

        linker_run(output_dir, input_args, mname, block.test.dset, block.train.dset)

