# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/upma',
                'doc_host': 'https://suchith720.github.io',
                'git_url': 'https://github.com/suchith720/upma',
                'lib_path': 'upma'},
  'syms': {'upma.core': {'upma.core.foo': ('core.html#foo', 'upma/core.py')}}}
