# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_ngame-for-msmarco-inference.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/00_ngame-for-msmarco-inference.ipynb 3
import os, torch,json, torch.multiprocessing as mp, joblib, numpy as np, scipy.sparse as sp, argparse
from tqdm.auto import tqdm

from xcai.basics import *
from xcai.analysis import *

from xcai.misc import BEIR_DATASETS
from xclib.utils.sparse import retain_topk
import xclib.evaluation.xc_metrics as xm


def _ndcg(eval_flags, n, k=5):
    _cumsum = 0
    _dcg = np.cumsum(np.multiply(
        eval_flags, 1/np.log2(np.arange(k)+2)),
        axis=-1)
    ndcg = []
    for _k in range(k):
        _cumsum += 1/np.log2(_k+1+1)
        ndcg.append(np.multiply(_dcg[:, _k].reshape(-1, 1), 1/np.minimum(n, _cumsum)))
    return np.hstack(ndcg)


def ndcg(X, true_labels, k=5, sorted=False, use_cython=False):
    indices, true_labels, _, _ = xm._setup_metric(
        X, true_labels, k=k, sorted=sorted, use_cython=use_cython)
    eval_flags = xm._eval_flags(indices, true_labels, None)
    _total_pos = np.asarray(
        true_labels.sum(axis=1),
        dtype=np.int32)
    _max_pos = max(np.max(_total_pos), k)
    _cumsum = np.cumsum(1/np.log2(np.arange(1, _max_pos+1)+1))
    n = _cumsum[_total_pos - 1]
    return _ndcg(eval_flags, n, k)


# %% ../nbs/00_ngame-for-msmarco-inference.ipynb 20
if __name__ == '__main__':
    output_dir = {
        "memory": "/home/sasokan/suchith/outputs/upma/20_upma-ngame-gpt-intent-substring-linker-with-tied-meta-encoder-for-msmarco-002/",
        "no_memory": "/home/sasokan/suchith/outputs/upma/20_upma-ngame-gpt-intent-substring-linker-with-tied-meta-encoder-for-msmarco-003/",
    }
    example_dir = "/home/sasokan/suchith/outputs/examples/"
    os.makedirs(f"{example_dir}/01-memory/", exist_ok=True)
    os.makedirs(f"{example_dir}/02-no_memory/", exist_ok=True)

    meta_file = "/home/sasokan/b-sprabhu/datasets/beir/msmarco/XC/intent_substring/conflation_01/raw_data/intent.raw.csv"
    linker_dir = "/home/sasokan/b-sprabhu/outputs/upma/07_msmarco-gpt-intent-substring-linker-with-ngame-loss-002/predictions/"

    meta_info = Info.from_txt(meta_file, info_column_names=["identifier", "input_text"])

    def get_sorted_keys(mat, i):
        return sorted(zip(mat[i].indices, mat[i].data), key=lambda x: x[1], reverse=True)

    def get_examples(data_lbl, data_info, lbl_info, data_meta, meta_info, mem_lbl, nme_lbl, idxs, scores):
        examples = []
        for i, score in zip(idxs, scores):
            examples.append({
                "query": data_info["input_text"][i],
                "labels": [(lbl_info["input_text"][idx], float(sc)) for idx, sc in get_sorted_keys(data_lbl, i)],
                "metadata": [(meta_info["input_text"][idx], float(sc)) for idx, sc in get_sorted_keys(data_meta, i)],
                "memory": [(lbl_info["input_text"][idx], float(sc)) for idx, sc in get_sorted_keys(mem_lbl, i)],
                "no memory": [(lbl_info["input_text"][idx], float(sc)) for idx, sc in get_sorted_keys(nme_lbl, i)],
                "score": score,
            })
        return examples


    for dataset in tqdm(BEIR_DATASETS):

        # load ground-truth 

        config_file = f"/data/datasets/beir/{dataset}/XC/configs/data.json"
        config_key, fname = get_config_key(config_file)
        with open(config_file) as file:
            config = json.load(file)[config_key]

        lbl_info = Info.from_txt(config["path"]["test"]["lbl_info"] if "lbl_info" in config["path"]["test"] else config["path"]["train"]["lbl_info"], 
                                 info_column_names=["identifier", "input_text"]) 

        tst_info = Info.from_txt(config["path"]["test"]["data_info"], info_column_names=["identifier", "input_text"]) 
        tst_lbl = sp.load_npz(config["path"]["test"]["data_lbl"]) 

        dataset = dataset.replace("/", "-")
        tst_meta = retain_topk(sp.load_npz(f"{linker_dir}/test_predictions_{dataset}.npz"), k=5)

        # load prediction

        mem_lbl = retain_topk(sp.load_npz(output_dir["memory"] + f"/predictions/test_predictions_{dataset}.npz"), k=10)
        nme_lbl = retain_topk(sp.load_npz(output_dir["no_memory"] + f"/predictions/test_predictions_{dataset}.npz"), k=10)

        # compute metric

        mem_scores = ndcg(mem_lbl, tst_lbl, k=10)[:, -1]
        nme_scores = ndcg(nme_lbl, tst_lbl, k=10)[:, -1]

        diff = mem_scores - nme_scores
        idxs = np.argsort(mem_scores - nme_scores)

        useful_idxs = idxs[-10:][::-1]
        mem_examples = get_examples(tst_lbl, tst_info, lbl_info, tst_meta, meta_info, mem_lbl, nme_lbl, useful_idxs, diff[useful_idxs])
        with open(f"{example_dir}/01-memory/{dataset}.json", "w") as file:
            json.dump(mem_examples, file, indent=4)

        useles_idxs = idxs[:10]
        nme_examples = get_examples(tst_lbl, tst_info, lbl_info, tst_meta, meta_info, mem_lbl, nme_lbl, useles_idxs, diff[useles_idxs])
        with open(f"{example_dir}/02-no_memory/{dataset}.json", "w") as file:
            json.dump(nme_examples, file, indent=4)



