# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/37_training-msmarco-distilbert-from-scratch.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/37_training-msmarco-distilbert-from-scratch.ipynb 2
import os, torch, json, torch.multiprocessing as mp, joblib, numpy as np, scipy.sparse as sp, argparse, time

from xcai.misc import *
from xcai.basics import *

os.environ["WANDB_PROJECT"] = "02_upma-msmarco-gpt-concept-substring"


# start latency analysis

import os, torch ,json, torch.multiprocessing as mp, joblib, numpy as np, scipy.sparse as sp, argparse
from typing import Optional, Union, Callable, List
from tqdm.auto import tqdm

from xclib.utils.sparse import retain_topk

from xcai.data import *
from xcai.sdata import SXCDataset, SMainXCDataset
from xcai.models.upma import UPA000, UPMAConfig

from torch.profiler import profile, ProfilerActivity


def upma_beir_inference(output_dir:str, input_args:argparse.ArgumentParser, mname:str, meta_save_fname:str, 
                        meta_file:str, linker_dir:str, data_dir:Optional[str]=None, n_data_lnk_samples:Optional[int]=5, n_lbl_lnk_samples:Optional[int]=5, 
                        data_lnk_topk:Optional[int]=5, lbl_lnk_topk:Optional[int]=5, eval_batch_size:Optional[int]=400, 
                        datasets:Optional[List]=None, data_repr_pooling:Optional[bool]=True, memory_injection_layer:Optional[Union[int, List]]=6, 
                        memory_type:Optional[Union[str, List]]="embeddings", n_memory_layers:Optional[int]=3, use_data_memory:Optional[bool]=True,
                        use_label_memory:Optional[bool]=False, num_input_metadata:Optional[int]=5, use_calib_loss:Optional[bool]=False, 
                        calib_loss_weight:Optional[float]=0.1, metric_dir_name:Optional[str]="metrics", pred_dir_name:Optional[str]=None, 
                        update_config_during_inference:Optional[bool]=False, tie_memory_encoder_weights:Optional[bool]=False, 
                        exclude_module_from_tying:Optional[str]=None, device:Optional[str]="cuda", no_memory:Optional[bool]=False, n_layers:Optional[int]=6):
    
    metric_dir = f"{output_dir}/{metric_dir_name}"
    os.makedirs(metric_dir, exist_ok=True)

    input_args.only_test = input_args.do_test_inference = input_args.save_test_prediction = True
    
    meta_info = load_info(f"{input_args.pickle_dir}/{meta_save_fname}.joblib", meta_file, mname, 
                          sequence_length=64)

    if data_dir is None: data_dir = "/data"
    
    datasets = BEIR_DATASETS if datasets is None else datasets

    metrics = {}
    for dataset in tqdm(datasets):
        print(dataset)

        config_file = f"{data_dir}/datasets/beir/{dataset}/XC/configs/data.json"
        train_dset, test_dset = load_upma_block(dataset, config_file, input_args)

        dataset = dataset.replace("/", "-")
        data_meta = retain_topk(sp.load_npz(f"{linker_dir}/test_predictions_{dataset}.npz"), k=data_lnk_topk)
        lbl_meta = (
            retain_topk(sp.load_npz(f"{linker_dir}/label_predictions_{dataset}.npz"), k=lbl_lnk_topk) 
            if use_label_memory else None
        )
        meta_kwargs = {
            "lnk_meta": SMetaXCDataset(prefix="lnk", data_meta=data_meta, lbl_meta=lbl_meta, meta_info=meta_info, n_sdata_meta_samples=n_data_lnk_samples,
                                       n_slbl_meta_samples=n_lbl_lnk_samples, return_scores=True, meta_oversample=True),
        }
        
        test_dset = SXCDataset(test_dset.data, **meta_kwargs)

        input_args.prediction_suffix = dataset
        latencies = upma_run(output_dir, input_args, mname, test_dset, train_dset, 
                             eval_batch_size=eval_batch_size, 
                             save_dir_name=pred_dir_name, 
                             data_repr_pooling=data_repr_pooling, 
                             memory_injection_layer=memory_injection_layer, 
                             use_data_memory=use_data_memory, 
                             use_label_memory=use_label_memory, 
                             memory_type=memory_type, 
                             n_memory_layers=n_memory_layers, 
                             num_input_metadata=num_input_metadata, 
                             use_calib_loss=use_calib_loss, 
                             calib_loss_weight=calib_loss_weight, 
                             update_config_during_inference=update_config_during_inference, 
                             tie_memory_encoder_weights=tie_memory_encoder_weights, 
                             exclude_module_from_tying=exclude_module_from_tying, 
                             no_memory=no_memory, device=device, n_layers=n_layers)

        print(latencies)
        metrics[dataset] = latencies

    return metrics
        

def upma_run(output_dir:str, input_args:argparse.ArgumentParser, mname:str, test_dset:Union[XCDataset, SXCDataset],
             train_dset:Optional[Union[XCDataset, SXCDataset]]=None, collator:Optional[Callable]=identity_collate_fn, 
             train_batch_size:Optional[int]=128, eval_batch_size:Optional[int]=400, save_dir_name:Optional[str]=None,
             data_repr_pooling:Optional[bool]=True, memory_injection_layer:Optional[Union[int, List]]=6, 
             memory_type:Optional[Union[str, List]]="embeddings", n_memory_layers:Optional[int]=3, use_data_memory:Optional[bool]=True,
             use_label_memory:Optional[bool]=False, num_input_metadata:Optional[int]=5, use_calib_loss:Optional[bool]=False, 
             calib_loss_weight:Optional[float]=0.1, update_config_during_inference:Optional[bool]=False, 
             tie_memory_encoder_weights:Optional[bool]=False, exclude_module_from_tying:Optional[str]=None, 
             resume_from_checkpoint:Optional[bool]=None, device:Optional[str]="cuda", no_memory:Optional[bool]=False, n_layers:Optional[int]=6):

    # data block features

    label_names = ["plbl2data_idx", "plbl2data_data2ptr"]

    if not no_memory: 
        label_names = label_names + ["lnk2data_idx", "lnk2data_data2ptr", "lnk2data_scores"]

    if "encoder" in memory_type: 
        label_names = label_names + ["lnk2data_input_ids", "lnk2data_attention_mask"]
    
    label_memory_names = ["lnk2lbl_idx", "lnk2lbl_data2ptr", "lnk2lbl_lbl2ptr", "lnk2lbl_scores", 
                          "lnk2neg_idx", "lnk2neg_data2ptr", "lnk2neg_neg2ptr", "lnk2neg_scores"]

    if "encoder" in memory_type:
        label_memory_names = label_memory_names + ["lnk2lbl_input_ids", "lnk2lbl_attention_mask", "lnk2neg_input_ids", "lnk2neg_attention_mask"]

    label_names = label_names + label_memory_names if use_label_memory else label_names

    # memory flags 

    if no_memory:
        use_data_memory = use_label_memory = False
    
    use_label_metadata = lbl2data_inject_memory = neg2data_inject_memory = use_label_memory

    data_inject_memory = use_data_memory

    memory_type = memory_type if isinstance(memory_type, list) else [memory_type]
    memory_injection_layer = memory_injection_layer if isinstance(memory_injection_layer, list) else [memory_injection_layer]

    # training arguements

    eval_batch_size = 400 if device == "cuda" else 16
    
    args = XCLearningArguments(
        output_dir=output_dir,
        logging_first_step=True,
        per_device_train_batch_size=train_batch_size,
        per_device_eval_batch_size=eval_batch_size,
        representation_num_beams=200,
        representation_accumulation_steps=10,
        save_strategy="steps",
        eval_strategy="steps",
        eval_steps=5000,
        save_steps=5000,
        save_total_limit=5,
        num_train_epochs=50,
        predict_with_representation=True,
        representation_search_type='BRUTEFORCE',
        search_normalize=False,

        adam_epsilon=1e-6,
        warmup_steps=1000,
        weight_decay=0.01,
        learning_rate=6e-5,
        label_names=label_names,

        group_by_cluster=True,
        use_data_metadata_for_clustering=True,
        num_clustering_warmup_epochs=10,
        num_cluster_update_epochs=5,
        num_cluster_size_update_epochs=25,
        clustering_type='EXPO',
        minimum_cluster_size=2,
        maximum_cluster_size=1600,

        data_aug_meta_name="lnk",
        use_label_metadata=use_label_metadata,

        metric_for_best_model='N@10',
        load_best_model_at_end=True,
        target_indices_key='plbl2data_idx',
        target_pointer_key='plbl2data_data2ptr',

        use_encoder_parallel=True,
        max_grad_norm=None,
        fp16=True if device == "cuda" else False,
        use_cpu=False if device == "cuda" else True,

        use_cpu_for_searching=True,
        use_cpu_for_clustering=True,
    )

    config = UPMAConfig(
        memory_module_names = memory_type,
        memory_injection_layers = memory_injection_layer,

        num_total_metadata = test_dset.meta["lnk_meta"].n_meta,
        num_input_metadata = num_input_metadata,
        metadata_dropout = 0.1,

        n_memory_layers = n_memory_layers,
        tie_memory_encoder_weights = tie_memory_encoder_weights,
        exclude_module_from_tying=exclude_module_from_tying,

        data_aug_meta_prefix="lnk2data",
        lbl2data_aug_meta_prefix="lnk2lbl",
        neg2data_aug_meta_prefix="lnk2neg",

        data_inject_memory=data_inject_memory,
        lbl2data_inject_memory=lbl2data_inject_memory,
        neg2data_inject_memory=neg2data_inject_memory,

        data_repr_pooling=data_repr_pooling,
        data_normalize=False,

        margin=0.3,
        num_negatives=10,
        tau=0.1,
        apply_softmax=True,
        reduction="mean",

        calib_margin=0.01,
        calib_num_negatives=10,
        calib_tau=0.1,
        calib_apply_softmax=False,

        calib_loss_weight=calib_loss_weight,
        use_calib_loss=use_calib_loss,

        use_encoder_parallel=True if device == "cuda" else False,
        loss_function="margin",

        initialize_memory_embeddings_from_injection_layer_mean=True,
        metadata_embedding_file=f"{output_dir}/metadata/gpt-substring.pth",

        n_layers=n_layers,
    )

    def model_fn(mname:Optional[str]=None):
        meta_dset = test_dset.meta_dset("lnk_meta")
        model = UPA000.from_pretrained(config, mname=mname, meta_dset=meta_dset, batch_size=1000)
        return model

    metric = PrecReclMrr(test_dset.n_lbl, test_dset.data.data_lbl_filterer, pk=10, rk=200, rep_pk=[1, 3, 5, 10],
                         rep_rk=[10, 100, 200], mk=[5, 10, 20])

    model = load_model(args.output_dir, model_fn, do_inference=check_inference_mode(input_args), use_pretrained=input_args.use_pretrained, 
                       update_config_during_inference=update_config_during_inference, config=config)

    learn = XCLearner(
        model=model,
        args=args,
        train_dataset=train_dset,
        eval_dataset=test_dset,
        data_collator=collator,
        compute_metrics=metric,
    )

    model = learn.model
    model.eval()

    model_param = sum(p.numel() for p in model.encoder.parameters())
    memory_param = sum(p.numel() for p in model.encoder.memory_modules[0].parameters())
    model_without_memory_param = model_param - memory_param

    dataloader = learn.get_test_dataloader(learn.eval_dataset)
    for inputs in dataloader:
        break

    with profile(activities=[ProfilerActivity.CPU, ProfilerActivity.CUDA], with_flops=True) as prof:
        with torch.no_grad():
            model(**inputs)
    flops = prof.key_averages().table(sort_by="flops", row_limit=10)

    return {
        "params": {
            "model": model_param, 
            "memory": memory_param, 
            "model_with_memory": model_without_memory_param
        }, 
        "memory": {
            "model": model_param * 4 / (1024**2), 
            "memory": memory_param * 4 / (1024**2), 
            "model_with_memory": model_without_memory_param * 4 / (1024**2)
        }, 
        "flops": flops,
        "seq_len": inputs["data_input_ids"].shape[1],
    }

# end latency analysis


def additional_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('--case', type=int, required=True)
    return parser.parse_known_args()[0]

    
# %% ../nbs/37_training-msmarco-distilbert-from-scratch.ipynb 21
if __name__ == '__main__':
    input_args = parse_args()
    extra_args = additional_args()

    output_dir = "/home/sasokan/b-sprabhu/outputs/upma/17_upma-with-ngame-gpt-intent-substring-linker-for-msmarco-with-calibration-loss-002/"

    input_args.use_sxc_sampler = True
    input_args.pickle_dir = "/data/suchith/datasets/processed/"
    mname = "distilbert-base-uncased"

    memory_injection_layer = 3
    meta_file = "/data/datasets/beir/msmarco/XC/intent_substring/conflation_01/raw_data/intent.raw.csv"
    linker_dir = "/home/sasokan/b-sprabhu/outputs/upma/07_msmarco-gpt-intent-substring-linker-with-ngame-loss-002/predictions/"

    device = "cuda"
    dir_name = "flops_and_memory"

    file_tag = "cuda_fp16" if device == "cuda" else "cpu_fp32"

    if extra_args.case == 1:
        # case 1
        n_layers = 6
        no_memory = update_config_during_inference = True
        save_file = f"/home/sasokan/suchith/outputs/timing/{dir_name}/07_msmarco-gpt-intent-substring-linker-with-ngame-loss-002_{file_tag}_no-memory_nlayers-06_flops-and-memory.json"

    elif extra_args.case == 2:
        # case 2
        n_layers = 6
        no_memory = update_config_during_inference = False

        if device == "cpu": update_config_during_inference = True

        save_file = f"/home/sasokan/suchith/outputs/timing/{dir_name}/07_msmarco-gpt-intent-substring-linker-with-ngame-loss-002_{file_tag}_memory_nlayers-06_flops-and-memory.json"

    elif extra_args.case == 3:
        # case 3
        n_layers = 12
        input_args.use_pretrained = True
        no_memory = update_config_during_inference = True
        save_file = f"/home/sasokan/suchith/outputs/timing/{dir_name}/07_msmarco-gpt-intent-substring-linker-with-ngame-loss-002_{file_tag}_no-memory_nlayers-12_flops-and-memory.json"

    else:
        raise ValueError("Invalid input")
    
    metrics = upma_beir_inference(output_dir, input_args, mname, "msmarco-intent-substring-conflation-01", meta_file, linker_dir, data_repr_pooling=False, 
                                  memory_injection_layer=memory_injection_layer, use_calib_loss=True, calib_loss_weight=0.1, device=device, no_memory=no_memory, 
                                  update_config_during_inference=update_config_during_inference, n_layers=n_layers)

    with open(save_file, "w") as file:
        json.dump(metrics, file, indent=4)

