# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_ngame-for-msmarco-inference.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/00_ngame-for-msmarco-inference.ipynb 3
import os, torch, json, joblib, numpy as np, scipy.sparse as sp, argparse
from tqdm.auto import tqdm

from xcai.basics import *
from xcai.analysis import *

from xcai.misc import BEIR_DATASETS
from xclib.utils.sparse import retain_topk
import xclib.evaluation.xc_metrics as xm

from sugar.core import *

# %% ../nbs/00_ngame-for-msmarco-inference.ipynb 20
if __name__ == '__main__':
    example_dir = "/home/sasokan/suchith/outputs/examples/"

    # Loading metadata

    # tst_ids, tst_txt = load_raw_file("/data/datasets/beir/msmarco/XC/raw_data/test.raw.csv")
    tst_ids, tst_txt = load_raw_file("/data/datasets/beir/msmarco/XC/raw_data/train.raw.csv")
    meta_ids, meta_txt = load_raw_file("/data/datasets/beir/msmarco/XC/raw_data/hipporag-fact.raw.csv")

    # tst_meta = "/data/outputs/maggi/00_nvembed-to-compute-msmarco-embeddings-002/predictions/beir/msmarco/test_facts.npz" 
    tst_meta = "/data/outputs/maggi/00_nvembed-to-compute-msmarco-embeddings-002/predictions/beir/msmarco/train_facts.npz" 
    tst_meta = sp.load_npz(tst_meta)
    tst_meta = retain_topk(tst_meta, k=5)

    # Loading labels

    lbl_ids, lbl_txt = load_raw_file("/data/datasets/beir/msmarco/XC/raw_data/label.raw.csv")
    # tst_lbl = sp.load_npz("/data/datasets/beir/msmarco/XC/tst_X_Y.npz")
    tst_lbl = sp.load_npz("/data/datasets/beir/msmarco/XC/trn_X_Y.npz")

    # Storing examples

    def get_sorted_keys(mat, i):
        return sorted(zip(mat[i].indices, mat[i].data), key=lambda x: x[1], reverse=True)

    idxs = np.random.permutation(tst_meta.shape[0])[:10]

    examples = []
    for i in idxs:
        examples.append({
            "query": tst_txt[i],
            "labels": [(lbl_txt[idx], float(sc)) for idx, sc in get_sorted_keys(tst_lbl, i)],
            "metadata": [(meta_txt[idx], float(sc)) for idx, sc in get_sorted_keys(tst_meta, i)],
        })

    # with open(f"{example_dir}/15-msmarco_test_hipporag_metadata.json", "w") as file:
    #     json.dump(examples, file, indent=4)

    with open(f"{example_dir}/16-msmarco_train_hipporag_metadata.json", "w") as file:
        json.dump(examples, file, indent=4)

