# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/37_training-msmarco-distilbert-from-scratch.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/37_training-msmarco-distilbert-from-scratch.ipynb 2
import os, torch, json, torch.multiprocessing as mp, joblib, numpy as np, scipy.sparse as sp, argparse, torch.nn as nn

from torch.utils.data import DataLoader

from xcai.misc import *
from xcai.basics import *

from xcai.learner import *
from xcai.main import *

# %% ../nbs/37_training-msmarco-distilbert-from-scratch.ipynb 4

os.environ["WANDB_PROJECT"] = "02_upma-msmarco-gpt-concept-substring"

class MyModel(nn.Module):

    def forward(self, **kwargs):
        for k,v in kwargs.items():
            if isinstance(v, torch.Tensor): print(k, ': ', v, ', ', v.device)
        return kwargs


# %% ../nbs/37_training-msmarco-distilbert-from-scratch.ipynb 21
if __name__ == '__main__':
    input_args = parse_args()

    input_args.use_sxc_sampler = True
    input_args.pickle_dir = "/data/suchith/datasets/processed/"
    config_file = "/home/sasokan/suchith/upma/configs/msmarco/hipporag/data_lbl_nvembed-hipporag-facts_ce-negatives-topk-05-linker_exact.json"

    train_dset, test_dset = load_upma_block("msmarco", config_file, input_args)

    m = XCDataParallel(module=MyModel())

    batch = DataLoader(train_dset, batch_size=10, collator=identity_collate_fn)
    o = m(**batch)

